/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { EventosGet$Params as EventosGet$Params } from './fn/consultas/eventos-get';
export { eventosGet as eventosGet } from './fn/consultas/eventos-get';
export type { EventosIdGet$Params as EventosIdGet$Params } from './fn/consultas/eventos-id-get';
export { eventosIdGet as eventosIdGet } from './fn/consultas/eventos-id-get';
export type { TrazasEntityTypeEntityIdGet$Params as TrazasEntityTypeEntityIdGet$Params } from './fn/trazas/trazas-entity-type-entity-id-get';
export { trazasEntityTypeEntityIdGet as trazasEntityTypeEntityIdGet } from './fn/trazas/trazas-entity-type-entity-id-get';
export type { CustodiaEvidenciasEvidenceIdGet$Params as CustodiaEvidenciasEvidenceIdGet$Params } from './fn/trazas/custodia-evidencias-evidence-id-get';
export { custodiaEvidenciasEvidenceIdGet as custodiaEvidenciasEvidenceIdGet } from './fn/trazas/custodia-evidencias-evidence-id-get';
export type { IntegridadVerificarGet$Params as IntegridadVerificarGet$Params } from './fn/integridad/integridad-verificar-get';
export { integridadVerificarGet as integridadVerificarGet } from './fn/integridad/integridad-verificar-get';
export type { InternoEventosPost$Params as InternoEventosPost$Params } from './fn/interno/interno-eventos-post';
export { internoEventosPost as internoEventosPost } from './fn/interno/interno-eventos-post';
