/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ConsultasService } from './services/consultas.service';
export { TrazasService } from './services/trazas.service';
export { IntegridadService } from './services/integridad.service';
export { InternoService } from './services/interno.service';
