/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { marcarLeida } from '../fn/buzon/marcar-leida';
import { MarcarLeida$Params } from '../fn/buzon/marcar-leida';
import { meGet } from '../fn/buzon/me-get';
import { MeGet$Params } from '../fn/buzon/me-get';
import { meLeidasPatch } from '../fn/buzon/me-leidas-patch';
import { MeLeidasPatch$Params } from '../fn/buzon/me-leidas-patch';
import { NotificacionResponse } from '../models/notificacion-response';


/**
 * Endpoints para el usuario final (Ciudadano/Staff).
 */
@Injectable({ providedIn: 'root' })
export class BuzonService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `meGet()` */
  static readonly MeGetPath = '/me';

  /**
   * Obtener mis notificaciones.
   *
   * Retorna el historial de alertas del usuario autenticado, ordenadas por fecha (más reciente primero).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `meGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  meGet$Response(params?: MeGet$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'items'?: Array<NotificacionResponse>;

/**
 * Contador total de mensajes sin leer (para el numerito rojo en la campana).
 */
'noLeidasCount'?: number;
}>> {
    const obs = meGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener mis notificaciones.
   *
   * Retorna el historial de alertas del usuario autenticado, ordenadas por fecha (más reciente primero).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `meGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  meGet(params?: MeGet$Params, context?: HttpContext): Promise<{
'items'?: Array<NotificacionResponse>;

/**
 * Contador total de mensajes sin leer (para el numerito rojo en la campana).
 */
'noLeidasCount'?: number;
}> {
    const resp = this.meGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'items'?: Array<NotificacionResponse>;

/**
 * Contador total de mensajes sin leer (para el numerito rojo en la campana).
 */
'noLeidasCount'?: number;
}>): {
'items'?: Array<NotificacionResponse>;

/**
 * Contador total de mensajes sin leer (para el numerito rojo en la campana).
 */
'noLeidasCount'?: number;
} => r.body);
  }

  /** Path part for operation `marcarLeida()` */
  static readonly MarcarLeidaPath = '/me/{id}/leida';

  /**
   * Marcar como leída.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `marcarLeida()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarLeida$Response(params: MarcarLeida$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = marcarLeida(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Marcar como leída.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `marcarLeida$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarLeida(params: MarcarLeida$Params, context?: HttpContext): Promise<void> {
    const resp = this.marcarLeida$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `meLeidasPatch()` */
  static readonly MeLeidasPatchPath = '/me/leidas';

  /**
   * Marcar todas mis notificaciones no leídas como leídas.
   *
   * Marca como leídas todas las notificaciones del usuario autenticado que aún estén en estado no leído. Operación idempotente: si no existen no leídas, no realiza cambios.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `meLeidasPatch()` instead.
   *
   * This method doesn't expect any request body.
   */
  meLeidasPatch$Response(params?: MeLeidasPatch$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = meLeidasPatch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Marcar todas mis notificaciones no leídas como leídas.
   *
   * Marca como leídas todas las notificaciones del usuario autenticado que aún estén en estado no leído. Operación idempotente: si no existen no leídas, no realiza cambios.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `meLeidasPatch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  meLeidasPatch(params?: MeLeidasPatch$Params, context?: HttpContext): Promise<void> {
    const resp = this.meLeidasPatch$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
