/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { internoDispararPost } from '../fn/interno/interno-disparar-post';
import { InternoDispararPost$Params } from '../fn/interno/interno-disparar-post';


/**
 * Endpoints S2S (Service-to-Service) restringidos. Solo otros microservicios pueden llamarlos.
 */
@Injectable({ providedIn: 'root' })
export class InternoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `internoDispararPost()` */
  static readonly InternoDispararPostPath = '/interno/disparar';

  /**
   * Enviar nueva notificación (Uso interno).
   *
   * Este endpoint es llamado por 'Denuncia Service' o 'Auth Service' cuando ocurre un evento. El servicio de notificaciones se encarga de: 1. Guardar en BD (Historial). 2. Enviar por WebSocket (Tiempo real). 3. Enviar correo electrónico (Async).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `internoDispararPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internoDispararPost$Response(params: InternoDispararPost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = internoDispararPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Enviar nueva notificación (Uso interno).
   *
   * Este endpoint es llamado por 'Denuncia Service' o 'Auth Service' cuando ocurre un evento. El servicio de notificaciones se encarga de: 1. Guardar en BD (Historial). 2. Enviar por WebSocket (Tiempo real). 3. Enviar correo electrónico (Async).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `internoDispararPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internoDispararPost(params: InternoDispararPost$Params, context?: HttpContext): Promise<void> {
    const resp = this.internoDispararPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
