/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { UsuarioAdminObtenerJefePorEntidad$Params as UsuarioAdminObtenerJefePorEntidad$Params } from './fn/admin/usuario-admin-obtener-jefe-por-entidad';
export { usuarioAdminObtenerJefePorEntidad as usuarioAdminObtenerJefePorEntidad } from './fn/admin/usuario-admin-obtener-jefe-por-entidad';
export type { UsuarioAdminObtenerOperadoresPorEntidad$Params as UsuarioAdminObtenerOperadoresPorEntidad$Params } from './fn/admin/usuario-admin-obtener-operadores-por-entidad';
export { usuarioAdminObtenerOperadoresPorEntidad as usuarioAdminObtenerOperadoresPorEntidad } from './fn/admin/usuario-admin-obtener-operadores-por-entidad';
export type { CrearCiudadano$Params as CrearCiudadano$Params } from './fn/interno/crear-ciudadano';
export { crearCiudadano as crearCiudadano } from './fn/interno/crear-ciudadano';
export type { CrearStaff$Params as CrearStaff$Params } from './fn/interno/crear-staff';
export { crearStaff as crearStaff } from './fn/interno/crear-staff';
export type { ObtenerUsuario$Params as ObtenerUsuario$Params } from './fn/interno/obtener-usuario';
export { obtenerUsuario as obtenerUsuario } from './fn/interno/obtener-usuario';
export type { ObtenerPorCedula$Params as ObtenerPorCedula$Params } from './fn/interno/obtener-por-cedula';
export { obtenerPorCedula as obtenerPorCedula } from './fn/interno/obtener-por-cedula';
export type { ObtenerPublico$Params as ObtenerPublico$Params } from './fn/interno/obtener-publico';
export { obtenerPublico as obtenerPublico } from './fn/interno/obtener-publico';
export type { ActualizarAlias$Params as ActualizarAlias$Params } from './fn/interno/actualizar-alias';
export { actualizarAlias as actualizarAlias } from './fn/interno/actualizar-alias';
export type { UsuarioInternoObtenerJefePorEntidad$Params as UsuarioInternoObtenerJefePorEntidad$Params } from './fn/interno/usuario-interno-obtener-jefe-por-entidad';
export { usuarioInternoObtenerJefePorEntidad as usuarioInternoObtenerJefePorEntidad } from './fn/interno/usuario-interno-obtener-jefe-por-entidad';
export type { UsuarioInternoObtenerOperadoresPorEntidad$Params as UsuarioInternoObtenerOperadoresPorEntidad$Params } from './fn/interno/usuario-interno-obtener-operadores-por-entidad';
export { usuarioInternoObtenerOperadoresPorEntidad as usuarioInternoObtenerOperadoresPorEntidad } from './fn/interno/usuario-interno-obtener-operadores-por-entidad';
