/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ObtenerJefePorEntidad$Params as ObtenerJefePorEntidad$Params } from './fn/operations/obtener-jefe-por-entidad';
export { obtenerJefePorEntidad as obtenerJefePorEntidad } from './fn/operations/obtener-jefe-por-entidad';
export type { ObtenerOperadoresPorEntidad$Params as ObtenerOperadoresPorEntidad$Params } from './fn/operations/obtener-operadores-por-entidad';
export { obtenerOperadoresPorEntidad as obtenerOperadoresPorEntidad } from './fn/operations/obtener-operadores-por-entidad';
export type { CrearCiudadano$Params as CrearCiudadano$Params } from './fn/operations/crear-ciudadano';
export { crearCiudadano as crearCiudadano } from './fn/operations/crear-ciudadano';
export type { CrearStaff$Params as CrearStaff$Params } from './fn/operations/crear-staff';
export { crearStaff as crearStaff } from './fn/operations/crear-staff';
export type { ObtenerUsuario$Params as ObtenerUsuario$Params } from './fn/operations/obtener-usuario';
export { obtenerUsuario as obtenerUsuario } from './fn/operations/obtener-usuario';
export type { ObtenerPorCedula$Params as ObtenerPorCedula$Params } from './fn/operations/obtener-por-cedula';
export { obtenerPorCedula as obtenerPorCedula } from './fn/operations/obtener-por-cedula';
export type { ObtenerPublico$Params as ObtenerPublico$Params } from './fn/operations/obtener-publico';
export { obtenerPublico as obtenerPublico } from './fn/operations/obtener-publico';
export type { ActualizarAlias$Params as ActualizarAlias$Params } from './fn/operations/actualizar-alias';
export { actualizarAlias as actualizarAlias } from './fn/operations/actualizar-alias';
export type { ObtenerJefePorEntidad_1$Params as ObtenerJefePorEntidad_1$Params } from './fn/operations/obtener-jefe-por-entidad-1';
export { obtenerJefePorEntidad_1 as obtenerJefePorEntidad_1 } from './fn/operations/obtener-jefe-por-entidad-1';
export type { ObtenerOperadoresPorEntidad_1$Params as ObtenerOperadoresPorEntidad_1$Params } from './fn/operations/obtener-operadores-por-entidad-1';
export { obtenerOperadoresPorEntidad_1 as obtenerOperadoresPorEntidad_1 } from './fn/operations/obtener-operadores-por-entidad-1';
