/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ActualizarAliasRequest } from './models/actualizar-alias-request';
export type { AliasResponse } from './models/alias-response';
export type { EntidadEnum } from './models/entidad-enum';
export type { EstadoUsuarioEnum } from './models/estado-usuario-enum';
export type { RegistroCiudadanoRequest } from './models/registro-ciudadano-request';
export type { RegistroStaffRequest } from './models/registro-staff-request';
export type { RolEnum } from './models/rol-enum';
export type { UsuarioPublicoResponse } from './models/usuario-publico-response';
export type { UsuarioResponse } from './models/usuario-response';
