/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntidadResponsableEnum } from '../../models/entidad-responsable-enum';

export interface AsignarEntidadADenuncia$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  denunciaId: number;
  entidad: EntidadResponsableEnum;
}

export function asignarEntidadADenuncia(http: HttpClient, rootUrl: string, params: AsignarEntidadADenuncia$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, asignarEntidadADenuncia.PATH, 'post');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.path('denunciaId', params.denunciaId, {});
    rb.query('entidad', params.entidad, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

asignarEntidadADenuncia.PATH = '/{denunciaId}/asignacion-entidad';
