/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DenunciaEstadoHistorialResponse } from '../../models/denuncia-estado-historial-response';

export interface DenunciaHistorialEstados$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  denunciaId: number;
}

export function denunciaHistorialEstados(http: HttpClient, rootUrl: string, params: DenunciaHistorialEstados$Params, context?: HttpContext): Observable<StrictHttpResponse<DenunciaEstadoHistorialResponse>> {
  const rb = new RequestBuilder(rootUrl, denunciaHistorialEstados.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.path('denunciaId', params.denunciaId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DenunciaEstadoHistorialResponse>;
    })
  );
}

denunciaHistorialEstados.PATH = '/{denunciaId}/historial-estados';
