/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioPerfilResponse } from '../../models/usuario-perfil-response';

export interface GetMe$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
}

export function getMe(http: HttpClient, rootUrl: string, params?: GetMe$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioPerfilResponse>> {
  const rb = new RequestBuilder(rootUrl, getMe.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioPerfilResponse>;
    })
  );
}

getMe.PATH = '/me';
