/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActualizarAliasRequest {

  /**
   * Alias público a mostrar a ciudadanos. El backend valida que no contenga PII ni coincida con nombre real.
   */
  aliasPublico: string;
}
