/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponse {

  /**
   * JWT token
   */
  accessToken?: string;

  /**
   * Segundos
   */
  expiresIn?: number;

  /**
   * Refresh token (rotación recomendada)
   */
  refreshToken?: string;
  tokenType?: string;
}
