/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadEnum } from './entidad-enum';

/**
 * Each possible value of `EntidadEnum`
 */
export const ENTIDAD_ENUM: EntidadEnum[] = [
  'MUNICIPIO',
  'EMPRESA_ELECTRICA',
  'EMPRESA_AGUA',
  'ASEO',
  'POLICIA'
];