/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Organización a la que pertenece el funcionario.
 */
export type EntidadEnum = 'MUNICIPIO' | 'EMPRESA_ELECTRICA' | 'EMPRESA_AGUA' | 'ASEO' | 'POLICIA';

