/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LogoutRequest {

  /**
   * Refresh token a revocar explícitamente si se usa un modelo donde el token no se infiere por contexto.
   */
  refreshToken?: string;
}
