/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasswordResetResponse {
  mensaje?: string;

  /**
   * Token de reseteo (dev only)
   */
  token?: string;
}
