/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefreshTokenRequest {

  /**
   * Refresh token vigente (rotación recomendada).
   */
  refreshToken: string;
}
