/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroCiudadanoRequest {

  /**
   * Dato sensible. No se expone a roles operativos.
   */
  cedula: string;
  email: string;

  /**
   * Dato sensible. Solo visible para el propio ciudadano y para perfiles estrictamente autorizados.
   */
  nombre: string;
  password: string;
}
