/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroStaffAuthRequest {
  aliasPublico?: string;

  /**
   * Cedula ecuatoriana (validador custom en código)
   */
  cedula: string;
  email: string;
  entidad: string;
  nombre: string;
  password?: string;
  rol: string;
}
