/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadEnum } from '../models/entidad-enum';
import { RolEnum } from '../models/rol-enum';
export interface RegistroStaffRequest {

  /**
   * Nombre visible para el ciudadano. Debe ser distinto al nombre real y no contener PII (email, cédula).
   */
  aliasPublico?: string;
  email: string;
  entidad: EntidadEnum;

  /**
   * Nombre real (no se muestra a ciudadanos).
   */
  nombre: string;
  rol: RolEnum;
}
