/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroUsuarioResponse {
  id?: number;
  mensaje?: string;

  /**
   * Identificador público pseudónimo del ciudadano. Solo aplica a rol CIUDADANO.
   */
  publicCitizenId?: string | null;
}
