/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadEnum } from '../models/entidad-enum';
import { RolEnum } from '../models/rol-enum';

/**
 * Respuesta minimizada para integraciones internas. No expone nombre real, email ni cédula.
 */
export interface UsuarioPublicoResponse {

  /**
   * Alias visible para ciudadanos si es staff.
   */
  aliasPublico?: string | null;
  entidad?: EntidadEnum;
  id?: number;

  /**
   * Identificador público pseudónimo si es ciudadano.
   */
  publicCitizenId?: string | null;
  rol?: RolEnum;
}
