/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadEnum } from '../models/entidad-enum';
import { RolEnum } from '../models/rol-enum';
export interface UsuarioPerfilResponse {

  /**
   * Alias público (aplica a roles de staff).
   */
  aliasPublico?: string | null;
  email?: string;
  entidad?: EntidadEnum;
  id?: number;

  /**
   * Campo sensible. Solo retorna para el propio usuario (frontend). No usar para integraciones internas.
   */
  nombre?: string;

  /**
   * Identificador público pseudónimo (aplica a CIUDADANO).
   */
  publicCitizenId?: string | null;
  rol?: RolEnum;
}
