/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioPublicoResponse } from '../../models/usuario-publico-response';

export interface GetUserPublicProfile$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  id: number;
}

export function getUserPublicProfile(http: HttpClient, rootUrl: string, params: GetUserPublicProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioPublicoResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserPublicProfile.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioPublicoResponse>;
    })
  );
}

getUserPublicProfile.PATH = '/users/{id}/public';
