/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistroStaffAuthRequest } from '../../models/registro-staff-auth-request';
import { RegistroUsuarioResponse } from '../../models/registro-usuario-response';

export interface RegistrarStaff$Params {
      body: RegistroStaffAuthRequest
}

export function registrarStaff(http: HttpClient, rootUrl: string, params: RegistrarStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<RegistroUsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, registrarStaff.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegistroUsuarioResponse>;
    })
  );
}

registrarStaff.PATH = '/register/staff';
