/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistroStaffRequest } from '../../models/registro-staff-request';
import { RegistroUsuarioResponse } from '../../models/registro-usuario-response';

export interface RegisterStaff$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
      body: RegistroStaffRequest
}

export function registerStaff(http: HttpClient, rootUrl: string, params: RegisterStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<RegistroUsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, registerStaff.PATH, 'post');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegistroUsuarioResponse>;
    })
  );
}

registerStaff.PATH = '/staff';
