/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificacionResponse } from '../../models/notificacion-response';

export interface MeGet$Params {

/**
 * Identificador de trazabilidad distribuida (propagado desde gateway).
 */
  'X-Correlation-Id'?: string;
  page?: number;

/**
 * Si es true, filtra solo las que no se han abierto.
 */
  soloNoLeidas?: boolean;
}

export function meGet(http: HttpClient, rootUrl: string, params?: MeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'items'?: Array<NotificacionResponse>;

/**
 * Contador total de mensajes sin leer (para el numerito rojo en la campana).
 */
'noLeidasCount'?: number;
}>> {
  const rb = new RequestBuilder(rootUrl, meGet.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.query('page', params.page, {});
    rb.query('soloNoLeidas', params.soloNoLeidas, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'items'?: Array<NotificacionResponse>;
      
      /**
       * Contador total de mensajes sin leer (para el numerito rojo en la campana).
       */
      'noLeidasCount'?: number;
      }>;
    })
  );
}

meGet.PATH = '/me';
