/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditAcceptedResponse } from '../../models/audit-accepted-response';
import { AuditIngestRequest } from '../../models/audit-ingest-request';

export interface InternoEventosPost$Params {
  'X-Correlation-Id'?: string;
      body: AuditIngestRequest
}

export function internoEventosPost(http: HttpClient, rootUrl: string, params: InternoEventosPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AuditAcceptedResponse>> {
  const rb = new RequestBuilder(rootUrl, internoEventosPost.PATH, 'post');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuditAcceptedResponse>;
    })
  );
}

internoEventosPost.PATH = '/interno/eventos';
