/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaEnum } from './categoria-enum';

/**
 * Each possible value of `CategoriaEnum`
 */
export const CATEGORIA_ENUM: CategoriaEnum[] = [
  'VIALIDAD',
  'AGUA',
  'ILUMINACION',
  'SEGURIDAD',
  'SANIDAD',
  'JARDINERIA',
  'OTROS'
];