/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaDenunciaEnum } from './categoria-denuncia-enum';

/**
 * Each possible value of `CategoriaDenunciaEnum`
 */
export const CATEGORIA_DENUNCIA_ENUM: CategoriaDenunciaEnum[] = [
  'VIALIDAD',
  'SANIDAD',
  'ILUMINACION',
  'JARDINERIA',
  'AGUA',
  'OTROS'
];