/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaEnum } from '../models/categoria-enum';
import { EvidenceId } from '../models/evidence-id';
import { NivelAnonimatoEnum } from '../models/nivel-anonimato-enum';
export interface CrearDenunciaRequest {
  categoria: CategoriaEnum;
  descripcion?: string;

  /**
   * Evidencias del ciudadano subidas y confirmadas previamente en el microservicio de evidencias (propósito CIUDADANO_CREACION). Denuncias solo recibe IDs, no URLs públicas.
   */
  evidenciaIds?: Array<EvidenceId>;
  latitud: number;
  longitud: number;
  nivelAnonimato: NivelAnonimatoEnum;
  titulo: string;
}
