/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaDenunciaEnum } from '../models/categoria-denuncia-enum';
import { NivelAnonimatoEnum } from '../models/nivel-anonimato-enum';
export interface CrearDenunciaRequest {
  categoriaDenuncia: CategoriaDenunciaEnum;
  descripcion: string;
  evidenciasIds: Array<string>;
  latitud: number;
  longitud: number;
  nivelAnonimato: NivelAnonimatoEnum;
  titulo: string;
}
