/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoDenunciaEnum } from '../models/estado-denuncia-enum';
import { EvidenceId } from '../models/evidence-id';
export interface DenunciaCitizenViewResponse {

  /**
   * Ej: 'Operador Marco' o 'Cuadrilla Eléctrica Norte'
   */
  asignadoA?: string;

  /**
   * Mensaje validado por el supervisor.
   */
  comentarioResolucion?: string;
  descripcion?: string;
  estado?: EstadoDenunciaEnum;

  /**
   * Evidencias aportadas por el ciudadano (visualizables por URL firmada desde el servicio de evidencias).
   */
  evidenciaIds?: Array<EvidenceId>;

  /**
   * Evidencias de resolución (solo visibles cuando el supervisor aprueba/expone al ciudadano).
   */
  evidenciaResolucionIds?: Array<EvidenceId>;
  id?: number;
  latitud?: number;
  longitud?: number;
  titulo?: string;
}
