/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoCambio } from '../models/estado-cambio';
export interface DenunciaEstadoHistorialResponse {
  denunciaId?: number;
  items?: Array<EstadoCambio>;
}
