/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoDenunciaEnum } from '../models/estado-denuncia-enum';
import { EvidenceId } from '../models/evidence-id';
export interface DenunciaStaffViewResponse {
  ciudadanoId?: number;
  comentarioTecnico?: string;

  /**
   * Si es ANÓNIMO viene null. Si es SEUDÓNIMO viene alias.
   */
  datosCiudadano?: string;
  estado?: EstadoDenunciaEnum;

  /**
   * Evidencias del ciudadano asociadas a la denuncia (acceso controlado por roles/permisos).
   */
  evidenciaIds?: Array<EvidenceId>;

  /**
   * Evidencias aportadas por el operador para sustentar la resolución.
   */
  evidenciaResolucionIds?: Array<EvidenceId>;
  feedbackSupervisor?: string;
  id?: number;
  operadorId?: number;
  titulo?: string;
}
