/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaDenunciaEnum } from '../models/categoria-denuncia-enum';
import { EntidadResponsableEnum } from '../models/entidad-responsable-enum';
import { EstadoDenunciaEnum } from '../models/estado-denuncia-enum';
import { EvidenciaDto } from '../models/evidencia-dto';
import { NivelAnonimatoEnum } from '../models/nivel-anonimato-enum';
import { Reporter } from '../models/reporter';
export interface DenunciaResponse {
  actualizadoEn?: string;
  categoriaDenuncia?: CategoriaDenunciaEnum;
  ciudadano?: Reporter;
  ciudadanoId?: number;
  comentarioObservacion?: string;
  comentarioResolucion?: string;
  creadoEn?: string;
  descripcion?: string;
  entidadResponsable?: EntidadResponsableEnum;
  estadoDenuncia?: EstadoDenunciaEnum;
  evidenciaCreacionIds?: Array<EvidenciaDto>;
  evidenciasResolucionIds?: Array<EvidenciaDto>;
  id?: number;
  jefe?: Reporter;
  jefeId?: number;
  latitud?: number;
  longitud?: number;
  nivelAnonimato?: NivelAnonimatoEnum;
  operador?: Reporter;
  operadorId?: number;
  titulo?: string;
}
