/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadResponsableEnum } from './entidad-responsable-enum';

/**
 * Each possible value of `EntidadResponsableEnum`
 */
export const ENTIDAD_RESPONSABLE_ENUM: EntidadResponsableEnum[] = [
  'MUNICIPIO',
  'EMPRESA_ELECTRICA',
  'EMPRESA_AGUA_POTABLE'
];