/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoDenunciaEnum } from './estado-denuncia-enum';

/**
 * Each possible value of `EstadoDenunciaEnum`
 */
export const ESTADO_DENUNCIA_ENUM: EstadoDenunciaEnum[] = [
  'RECIBIDA',
  'ASIGNADA',
  'EN_PROCESO',
  'EN_VALIDACION',
  'RESUELTA',
  'RECHAZADA'
];