/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * - RECIBIDA: Recién creada. - ASIGNADA: Jefe asignó a Operador. - EN_PROCESO: Operador aceptó y trabaja. - EN_VALIDACION: Operador terminó, Supervisor revisa. - RESUELTA: Supervisor aprobó.
 */
export type EstadoDenunciaEnum = 'RECIBIDA' | 'ASIGNADA' | 'EN_PROCESO' | 'EN_VALIDACION' | 'RESUELTA' | 'RECHAZADA';

