/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoDenunciaEnum } from '../models/estado-denuncia-enum';
export interface EstadoCambio {
  actorId?: number;
  estadoAnterior?: EstadoDenunciaEnum;
  estadoNuevo?: EstadoDenunciaEnum;
  ocurridoEn?: string;
}
