/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NivelAnonimatoEnum } from './nivel-anonimato-enum';

/**
 * Each possible value of `NivelAnonimatoEnum`
 */
export const NIVEL_ANONIMATO_ENUM: NivelAnonimatoEnum[] = [
  'REAL',
  'SEUDONIMO',
  'ANONIMO'
];