/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Nivel de privacidad elegido por el ciudadano.
 */
export type NivelAnonimatoEnum = 'REAL' | 'SEUDONIMO' | 'ANONIMO';

