/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoUsuarioEnum } from './estado-usuario-enum';

/**
 * Each possible value of `EstadoUsuarioEnum`
 */
export const ESTADO_USUARIO_ENUM: EstadoUsuarioEnum[] = [
  'ACTIVO',
  'BLOQUEADO'
];