/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroCiudadanoRequest {

  /**
   * Cedula ecuatoriana (validador custom en código)
   */
  cedula: string;
  email: string;
  nombre: string;
}
