/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadEnum } from '../models/entidad-enum';
import { RolEnum } from '../models/rol-enum';
export interface RegistroStaffRequest {
  aliasPublico?: string;

  /**
   * Cedula ecuatoriana (validador custom en código)
   */
  cedula: string;
  email: string;
  entidad: EntidadEnum;
  nombre: string;
  rol: RolEnum;
}
