/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RolEnum } from './rol-enum';

/**
 * Each possible value of `RolEnum`
 */
export const ROL_ENUM: RolEnum[] = [
  'ADMIN',
  'SUPERVISOR',
  'JEFE_OP_INT',
  'JEFE_OP_EXT',
  'OP_INT',
  'OP_EXT',
  'CIUDADANO'
];