/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadEnum } from '../models/entidad-enum';
import { EstadoUsuarioEnum } from '../models/estado-usuario-enum';
import { RolEnum } from '../models/rol-enum';
export interface UsuarioResponse {
  aliasPublico?: string;
  cedula?: string;
  email?: string;
  entidad?: EntidadEnum;
  estado?: EstadoUsuarioEnum;
  id?: number;
  nombre?: string;
  rol?: RolEnum;
}
