/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadEnum } from '../models/entidad-enum';
import { RolEnum } from '../models/rol-enum';
export interface UsuarioPublicoResponse {
  aliasPublico?: string;
  entidad?: EntidadEnum;
  id?: number;
  publicCitizenId?: string;
  rol?: RolEnum;
}
