/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearDenunciaRequest } from '../../models/crear-denuncia-request';
import { DenunciaResumenResponse } from '../../models/denuncia-resumen-response';

export interface CrearDenuncia$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
      body: CrearDenunciaRequest
}

export function crearDenuncia(http: HttpClient, rootUrl: string, params: CrearDenuncia$Params, context?: HttpContext): Observable<StrictHttpResponse<DenunciaResumenResponse>> {
  const rb = new RequestBuilder(rootUrl, crearDenuncia.PATH, 'post');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DenunciaResumenResponse>;
    })
  );
}

crearDenuncia.PATH = '/denuncias';
