/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DenunciaResponse } from '../../models/denuncia-response';

export interface ObtenerDenunciaPorId$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  denunciaId: number;
}

export function obtenerDenunciaPorId(http: HttpClient, rootUrl: string, params: ObtenerDenunciaPorId$Params, context?: HttpContext): Observable<StrictHttpResponse<DenunciaResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerDenunciaPorId.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.path('denunciaId', params.denunciaId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DenunciaResponse>;
    })
  );
}

obtenerDenunciaPorId.PATH = '/{denunciaId}';
