/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EvidenciaMetadataResponse } from '../../models/evidencia-metadata-response';

export interface EvidenciasIdGet$Params {
  id: string;
  'X-Correlation-Id'?: string;
}

export function evidenciasIdGet(http: HttpClient, rootUrl: string, params: EvidenciasIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EvidenciaMetadataResponse>> {
  const rb = new RequestBuilder(rootUrl, evidenciasIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EvidenciaMetadataResponse>;
    })
  );
}

evidenciasIdGet.PATH = '/evidencias/{id}';
