/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModoUrlEnum } from '../../models/modo-url-enum';
import { UrlFirmadaResponse } from '../../models/url-firmada-response';

export interface EvidenciasIdUrlFirmadaGet$Params {
  id: string;
  modo?: ModoUrlEnum;
  'X-Correlation-Id'?: string;
}

export function evidenciasIdUrlFirmadaGet(http: HttpClient, rootUrl: string, params: EvidenciasIdUrlFirmadaGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UrlFirmadaResponse>> {
  const rb = new RequestBuilder(rootUrl, evidenciasIdUrlFirmadaGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('modo', params.modo, {});
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrlFirmadaResponse>;
    })
  );
}

evidenciasIdUrlFirmadaGet.PATH = '/evidencias/{id}/url-firmada';
