/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdjuntarEvidencias$Params as AdjuntarEvidencias$Params } from './fn/interno/adjuntar-evidencias';
export { adjuntarEvidencias as adjuntarEvidencias } from './fn/interno/adjuntar-evidencias';
export type { ObtenerEvidencias$Params as ObtenerEvidencias$Params } from './fn/interno/obtener-evidencias';
export { obtenerEvidencias as obtenerEvidencias } from './fn/interno/obtener-evidencias';
export type { ConfirmarCarga$Params as ConfirmarCarga$Params } from './fn/interno/confirmar-carga';
export { confirmarCarga as confirmarCarga } from './fn/interno/confirmar-carga';
export type { CrearIntencionDeCarga$Params as CrearIntencionDeCarga$Params } from './fn/interno/crear-intencion-de-carga';
export { crearIntencionDeCarga as crearIntencionDeCarga } from './fn/interno/crear-intencion-de-carga';
