/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { UploadsPost$Params as UploadsPost$Params } from './fn/uploads/uploads-post';
export { uploadsPost as uploadsPost } from './fn/uploads/uploads-post';
export type { UploadsUploadIdConfirmarPost$Params as UploadsUploadIdConfirmarPost$Params } from './fn/uploads/uploads-upload-id-confirmar-post';
export { uploadsUploadIdConfirmarPost as uploadsUploadIdConfirmarPost } from './fn/uploads/uploads-upload-id-confirmar-post';
export type { EvidenciasIdGet$Params as EvidenciasIdGet$Params } from './fn/evidencias/evidencias-id-get';
export { evidenciasIdGet as evidenciasIdGet } from './fn/evidencias/evidencias-id-get';
export type { EvidenciasIdUrlFirmadaGet$Params as EvidenciasIdUrlFirmadaGet$Params } from './fn/evidencias/evidencias-id-url-firmada-get';
export { evidenciasIdUrlFirmadaGet as evidenciasIdUrlFirmadaGet } from './fn/evidencias/evidencias-id-url-firmada-get';
export type { InternoAdjuntarPost$Params as InternoAdjuntarPost$Params } from './fn/interno/interno-adjuntar-post';
export { internoAdjuntarPost as internoAdjuntarPost } from './fn/interno/interno-adjuntar-post';
export type { InternoEntidadesTipoEntidadIdEvidenciasGet$Params as InternoEntidadesTipoEntidadIdEvidenciasGet$Params } from './fn/interno/interno-entidades-tipo-entidad-id-evidencias-get';
export { internoEntidadesTipoEntidadIdEvidenciasGet as internoEntidadesTipoEntidadIdEvidenciasGet } from './fn/interno/interno-entidades-tipo-entidad-id-evidencias-get';
