/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdjuntarEvidenciaRequest } from './models/adjuntar-evidencia-request';
export type { EntidadTipoEnum } from './models/entidad-tipo-enum';
export type { ErrorResponse } from './models/error-response';
export type { EstadoEvidenciaEnum } from './models/estado-evidencia-enum';
export type { EvidenciaInternaResponse } from './models/evidencia-interna-response';
