/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdjuntarEvidenciasRequest } from './models/adjuntar-evidencias-request';
export type { AdjuntarEvidenciasResponse } from './models/adjuntar-evidencias-response';
export type { ArchivoPreCargaRequest } from './models/archivo-pre-carga-request';
export type { ComprobanteUpload } from './models/comprobante-upload';
export type { ConfirmarUploadRequest } from './models/confirmar-upload-request';
export type { ConfirmarUploadResponse } from './models/confirmar-upload-response';
export type { CrearUploadRequest } from './models/crear-upload-request';
export type { CrearUploadResponse } from './models/crear-upload-response';
export type { EntidadTipoEnum } from './models/entidad-tipo-enum';
export type { ErrorResponse } from './models/error-response';
export type { EstadoEvidenciaEnum } from './models/estado-evidencia-enum';
export type { EvidenciaInternaResponse } from './models/evidencia-interna-response';
export type { EvidenciaMetadataResponse } from './models/evidencia-metadata-response';
export type { ModoUrlEnum } from './models/modo-url-enum';
export type { PermisosEvidenciaRequest } from './models/permisos-evidencia-request';
export type { PropositoEvidenciaEnum } from './models/proposito-evidencia-enum';
export type { RestriccionesUploadRequest } from './models/restricciones-upload-request';
export type { RolEnum } from './models/rol-enum';
export type { UploadItemResponse } from './models/upload-item-response';
export type { UrlFirmadaResponse } from './models/url-firmada-response';
