/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UploadsService } from './services/uploads.service';
export { EvidenciasService } from './services/evidencias.service';
export { InternoService } from './services/interno.service';
