/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EvidenceId } from '../../models/evidence-id';

export interface DenunciasIdResolucionPatch$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  id: number;
      body: {
'comentarioTecnico'?: string;

/**
 * Evidencias de resolución subidas y confirmadas previamente en el microservicio de evidencias (propósito OPERADOR_RESOLUCION).
 */
'evidenciaIds'?: Array<EvidenceId>;
}
}

export function denunciasIdResolucionPatch(http: HttpClient, rootUrl: string, params: DenunciasIdResolucionPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, denunciasIdResolucionPatch.PATH, 'patch');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

denunciasIdResolucionPatch.PATH = '/denuncias/{id}/resolucion';
