/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DenunciaStaffViewResponse } from '../../models/denuncia-staff-view-response';
import { EstadoDenunciaEnum } from '../../models/estado-denuncia-enum';

export interface DenunciasGestionGet$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  estado?: EstadoDenunciaEnum;
  page?: number;
}

export function denunciasGestionGet(http: HttpClient, rootUrl: string, params?: DenunciasGestionGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DenunciaStaffViewResponse>>> {
  const rb = new RequestBuilder(rootUrl, denunciasGestionGet.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.query('estado', params.estado, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DenunciaStaffViewResponse>>;
    })
  );
}

denunciasGestionGet.PATH = '/denuncias/gestion';
