/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { EvidenciaMetadataResponse } from '../models/evidencia-metadata-response';
import { evidenciasIdGet } from '../fn/evidencias/evidencias-id-get';
import { EvidenciasIdGet$Params } from '../fn/evidencias/evidencias-id-get';
import { evidenciasIdUrlFirmadaGet } from '../fn/evidencias/evidencias-id-url-firmada-get';
import { EvidenciasIdUrlFirmadaGet$Params } from '../fn/evidencias/evidencias-id-url-firmada-get';
import { UrlFirmadaResponse } from '../models/url-firmada-response';


/**
 * Consulta segura y obtención de URLs firmadas.
 */
@Injectable({ providedIn: 'root' })
export class EvidenciasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `evidenciasIdGet()` */
  static readonly EvidenciasIdGetPath = '/evidencias/{id}';

  /**
   * Obtener metadatos de evidencia.
   *
   * Retorna metadatos no sensibles de la evidencia, sujeto a control de acceso. No retorna URL directa; para acceso al archivo se usa el endpoint de URL firmada.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `evidenciasIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  evidenciasIdGet$Response(params: EvidenciasIdGet$Params, context?: HttpContext): Promise<StrictHttpResponse<EvidenciaMetadataResponse>> {
    const obs = evidenciasIdGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener metadatos de evidencia.
   *
   * Retorna metadatos no sensibles de la evidencia, sujeto a control de acceso. No retorna URL directa; para acceso al archivo se usa el endpoint de URL firmada.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `evidenciasIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  evidenciasIdGet(params: EvidenciasIdGet$Params, context?: HttpContext): Promise<EvidenciaMetadataResponse> {
    const resp = this.evidenciasIdGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<EvidenciaMetadataResponse>): EvidenciaMetadataResponse => r.body);
  }

  /** Path part for operation `evidenciasIdUrlFirmadaGet()` */
  static readonly EvidenciasIdUrlFirmadaGetPath = '/evidencias/{id}/url-firmada';

  /**
   * Obtener URL firmada de descarga o preview.
   *
   * Retorna una URL firmada (expirable) para descargar o visualizar la evidencia. El servicio valida permisos antes de emitir la URL.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `evidenciasIdUrlFirmadaGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  evidenciasIdUrlFirmadaGet$Response(params: EvidenciasIdUrlFirmadaGet$Params, context?: HttpContext): Promise<StrictHttpResponse<UrlFirmadaResponse>> {
    const obs = evidenciasIdUrlFirmadaGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener URL firmada de descarga o preview.
   *
   * Retorna una URL firmada (expirable) para descargar o visualizar la evidencia. El servicio valida permisos antes de emitir la URL.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `evidenciasIdUrlFirmadaGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  evidenciasIdUrlFirmadaGet(params: EvidenciasIdUrlFirmadaGet$Params, context?: HttpContext): Promise<UrlFirmadaResponse> {
    const resp = this.evidenciasIdUrlFirmadaGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<UrlFirmadaResponse>): UrlFirmadaResponse => r.body);
  }

}
