/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AdjuntarEvidenciasResponse } from '../models/adjuntar-evidencias-response';
import { EvidenciaInternaResponse } from '../models/evidencia-interna-response';
import { internoAdjuntarPost } from '../fn/interno/interno-adjuntar-post';
import { InternoAdjuntarPost$Params } from '../fn/interno/interno-adjuntar-post';
import { internoEntidadesTipoEntidadIdEvidenciasGet } from '../fn/interno/interno-entidades-tipo-entidad-id-evidencias-get';
import { InternoEntidadesTipoEntidadIdEvidenciasGet$Params } from '../fn/interno/interno-entidades-tipo-entidad-id-evidencias-get';


/**
 * Endpoints S2S (Service-to-Service) para adjuntar evidencias a denuncias y gestionar permisos.
 */
@Injectable({ providedIn: 'root' })
export class InternoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `internoAdjuntarPost()` */
  static readonly InternoAdjuntarPostPath = '/interno/adjuntar';

  /**
   * Adjuntar evidencias a una entidad de negocio.
   *
   * Endpoint S2S: permite a otros microservicios (principalmente Denuncias) adjuntar evidencias a una entidad (por ejemplo, una denuncia). Puede establecer permisos explícitos por rol/usuarios. Este endpoint evita que Denuncias deba conocer el storage.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `internoAdjuntarPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internoAdjuntarPost$Response(params: InternoAdjuntarPost$Params, context?: HttpContext): Promise<StrictHttpResponse<AdjuntarEvidenciasResponse>> {
    const obs = internoAdjuntarPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Adjuntar evidencias a una entidad de negocio.
   *
   * Endpoint S2S: permite a otros microservicios (principalmente Denuncias) adjuntar evidencias a una entidad (por ejemplo, una denuncia). Puede establecer permisos explícitos por rol/usuarios. Este endpoint evita que Denuncias deba conocer el storage.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `internoAdjuntarPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internoAdjuntarPost(params: InternoAdjuntarPost$Params, context?: HttpContext): Promise<AdjuntarEvidenciasResponse> {
    const resp = this.internoAdjuntarPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdjuntarEvidenciasResponse>): AdjuntarEvidenciasResponse => r.body);
  }

  /** Path part for operation `internoEntidadesTipoEntidadIdEvidenciasGet()` */
  static readonly InternoEntidadesTipoEntidadIdEvidenciasGetPath = '/interno/entidades/{tipo}/{entidadId}/evidencias';

  /**
   * Listar evidencias de una entidad (S2S).
   *
   * Endpoint S2S para consultar evidencias adjuntas a una entidad de negocio (ej. una denuncia), usado por Denuncias para componer respuestas (sin exponer URLs públicas).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `internoEntidadesTipoEntidadIdEvidenciasGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  internoEntidadesTipoEntidadIdEvidenciasGet$Response(params: InternoEntidadesTipoEntidadIdEvidenciasGet$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<EvidenciaInternaResponse>>> {
    const obs = internoEntidadesTipoEntidadIdEvidenciasGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Listar evidencias de una entidad (S2S).
   *
   * Endpoint S2S para consultar evidencias adjuntas a una entidad de negocio (ej. una denuncia), usado por Denuncias para componer respuestas (sin exponer URLs públicas).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `internoEntidadesTipoEntidadIdEvidenciasGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  internoEntidadesTipoEntidadIdEvidenciasGet(params: InternoEntidadesTipoEntidadIdEvidenciasGet$Params, context?: HttpContext): Promise<Array<EvidenciaInternaResponse>> {
    const resp = this.internoEntidadesTipoEntidadIdEvidenciasGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<EvidenciaInternaResponse>>): Array<EvidenciaInternaResponse> => r.body);
  }

}
