/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ConfirmarUploadResponse } from '../models/confirmar-upload-response';
import { CrearUploadResponse } from '../models/crear-upload-response';
import { uploadsPost } from '../fn/uploads/uploads-post';
import { UploadsPost$Params } from '../fn/uploads/uploads-post';
import { uploadsUploadIdConfirmarPost } from '../fn/uploads/uploads-upload-id-confirmar-post';
import { UploadsUploadIdConfirmarPost$Params } from '../fn/uploads/uploads-upload-id-confirmar-post';


/**
 * Flujo de pre-carga y confirmación de archivos.
 */
@Injectable({ providedIn: 'root' })
export class UploadsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `uploadsPost()` */
  static readonly UploadsPostPath = '/uploads';

  /**
   * Crear sesión de pre-carga.
   *
   * Crea una sesión de subida y devuelve URLs firmadas para subir directamente al storage. El archivo se sube fuera del servicio (por URL firmada). Luego el cliente confirma la carga.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadsPost$Response(params: UploadsPost$Params, context?: HttpContext): Promise<StrictHttpResponse<CrearUploadResponse>> {
    const obs = uploadsPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear sesión de pre-carga.
   *
   * Crea una sesión de subida y devuelve URLs firmadas para subir directamente al storage. El archivo se sube fuera del servicio (por URL firmada). Luego el cliente confirma la carga.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadsPost(params: UploadsPost$Params, context?: HttpContext): Promise<CrearUploadResponse> {
    const resp = this.uploadsPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<CrearUploadResponse>): CrearUploadResponse => r.body);
  }

  /** Path part for operation `uploadsUploadIdConfirmarPost()` */
  static readonly UploadsUploadIdConfirmarPostPath = '/uploads/{uploadId}/confirmar';

  /**
   * Confirmar carga de archivos.
   *
   * Confirma que el/los archivos fueron subidos exitosamente al storage. El servicio valida metadatos, aplica normalización (p. ej. eliminación EXIF) y cambia el estado a DISPONIBLE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadsUploadIdConfirmarPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadsUploadIdConfirmarPost$Response(params: UploadsUploadIdConfirmarPost$Params, context?: HttpContext): Promise<StrictHttpResponse<ConfirmarUploadResponse>> {
    const obs = uploadsUploadIdConfirmarPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Confirmar carga de archivos.
   *
   * Confirma que el/los archivos fueron subidos exitosamente al storage. El servicio valida metadatos, aplica normalización (p. ej. eliminación EXIF) y cambia el estado a DISPONIBLE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadsUploadIdConfirmarPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadsUploadIdConfirmarPost(params: UploadsUploadIdConfirmarPost$Params, context?: HttpContext): Promise<ConfirmarUploadResponse> {
    const resp = this.uploadsUploadIdConfirmarPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConfirmarUploadResponse>): ConfirmarUploadResponse => r.body);
  }

}
