/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoEventoEnum } from '../models/tipo-evento-enum';
export interface CrearNotificacionInternaRequest {

  /**
   * Por qué medios se debe intentar contactar.
   */
  canales?: Array<'IN_APP' | 'EMAIL' | 'PUSH'>;

  /**
   * ID de la entidad relacionada - ej ID de la Denuncia). Sirve para hacer link.
   */
  entidadId?: number;
  mensaje: string;
  tipoEvento: TipoEventoEnum;
  titulo: string;

  /**
   * ID del usuario que recibirá la alerta (extraído de Auth).
   */
  usuarioDestinoId: number;
}
