/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoEventoEnum } from '../models/tipo-evento-enum';
export interface NotificacionResponse {

  /**
   * ID para redirigir al usuario al detalle - ej ID denuncia.
   */
  entidadId?: number;
  fechaCreacion?: string;
  id?: number;
  leida?: boolean;
  mensaje?: string;
  tipoEvento?: TipoEventoEnum;
  titulo?: string;
}
