/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PrioridadEnum } from './prioridad-enum';

/**
 * Each possible value of `PrioridadEnum`
 */
export const PRIORIDAD_ENUM: PrioridadEnum[] = [
  'ALTA',
  'MEDIA',
  'BAJA'
];