/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type TipoEventoEnum = 'DENUNCIA_CREADA' | 'DENUNCIA_ASIGNADA' | 'DENUNCIA_RESUELTA' | 'DENUNCIA_RECHAZADA' | 'VALIDACION_REQUERIDA' | 'BIENVENIDA_USUARIO';

