/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoEventoEnum } from './tipo-evento-enum';

/**
 * Each possible value of `TipoEventoEnum`
 */
export const TIPO_EVENTO_ENUM: TipoEventoEnum[] = [
  'DENUNCIA_CREADA',
  'DENUNCIA_ASIGNADA',
  'DENUNCIA_RESUELTA',
  'DENUNCIA_RECHAZADA',
  'VALIDACION_REQUERIDA',
  'BIENVENIDA_USUARIO'
];