/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { registrarStaff } from '../fn/admin/registrar-staff';
import { RegistrarStaff$Params } from '../fn/admin/registrar-staff';
import { RegistroUsuarioResponse } from '../models/registro-usuario-response';


/**
 * Operaciones administrativas (registro de staff).
 */
@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registrarStaff()` */
  static readonly RegistrarStaffPath = '/register/staff';

  /**
   * Registrar funcionario (Operador, Jefe, Supervisor).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrarStaff()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarStaff$Response(params: RegistrarStaff$Params, context?: HttpContext): Promise<StrictHttpResponse<RegistroUsuarioResponse>> {
    const obs = registrarStaff(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Registrar funcionario (Operador, Jefe, Supervisor).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrarStaff$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarStaff(params: RegistrarStaff$Params, context?: HttpContext): Promise<RegistroUsuarioResponse> {
    const resp = this.registrarStaff$Response(params, context);
    return resp.then((r: StrictHttpResponse<RegistroUsuarioResponse>): RegistroUsuarioResponse => r.body);
  }

}
