/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AliasResponse } from '../models/alias-response';
import { getMe } from '../fn/cuenta/get-me';
import { GetMe$Params } from '../fn/cuenta/get-me';
import { logout } from '../fn/cuenta/logout';
import { Logout$Params } from '../fn/cuenta/logout';
import { updateMyAlias } from '../fn/cuenta/update-my-alias';
import { UpdateMyAlias$Params } from '../fn/cuenta/update-my-alias';
import { UsuarioPerfilResponse } from '../models/usuario-perfil-response';


/**
 * Gestión de la propia cuenta.
 */
@Injectable({ providedIn: 'root' })
export class CuentaService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMe()` */
  static readonly GetMePath = '/me';

  /**
   * Obtener perfil actual.
   *
   * Permite al frontend saber quién está logueado y qué rol tiene. Para consumo interno entre microservicios, usar endpoints de perfil público/minimizado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMe$Response(params?: GetMe$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioPerfilResponse>> {
    const obs = getMe(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener perfil actual.
   *
   * Permite al frontend saber quién está logueado y qué rol tiene. Para consumo interno entre microservicios, usar endpoints de perfil público/minimizado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMe(params?: GetMe$Params, context?: HttpContext): Promise<UsuarioPerfilResponse> {
    const resp = this.getMe$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioPerfilResponse>): UsuarioPerfilResponse => r.body);
  }

  /** Path part for operation `updateMyAlias()` */
  static readonly UpdateMyAliasPath = '/me/alias';

  /**
   * Actualizar alias público.
   *
   * Permite a roles de staff establecer o actualizar el alias público que verán los ciudadanos. Reglas: no debe contener email, cédula ni nombres reales; el backend valida y puede rechazar. Si el rol es CIUDADANO, este endpoint se rechaza.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMyAlias()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyAlias$Response(params: UpdateMyAlias$Params, context?: HttpContext): Promise<StrictHttpResponse<AliasResponse>> {
    const obs = updateMyAlias(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Actualizar alias público.
   *
   * Permite a roles de staff establecer o actualizar el alias público que verán los ciudadanos. Reglas: no debe contener email, cédula ni nombres reales; el backend valida y puede rechazar. Si el rol es CIUDADANO, este endpoint se rechaza.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMyAlias$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyAlias(params: UpdateMyAlias$Params, context?: HttpContext): Promise<AliasResponse> {
    const resp = this.updateMyAlias$Response(params, context);
    return resp.then((r: StrictHttpResponse<AliasResponse>): AliasResponse => r.body);
  }

  /** Path part for operation `logout()` */
  static readonly LogoutPath = '/logout';

  /**
   * Cerrar sesión actual.
   *
   * Invalida el refresh token entregado (revocación) para impedir futuras renovaciones. Si se usa un modelo estrictamente stateless sin revocación, el cliente solo elimina tokens localmente.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logout()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  logout$Response(params?: Logout$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = logout(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cerrar sesión actual.
   *
   * Invalida el refresh token entregado (revocación) para impedir futuras renovaciones. Si se usa un modelo estrictamente stateless sin revocación, el cliente solo elimina tokens localmente.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logout$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  logout(params?: Logout$Params, context?: HttpContext): Promise<void> {
    const resp = this.logout$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
