/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuthResponse } from '../models/auth-response';
import { forgotPassword } from '../fn/publico/forgot-password';
import { ForgotPassword$Params } from '../fn/publico/forgot-password';
import { login } from '../fn/publico/login';
import { Login$Params } from '../fn/publico/login';
import { refreshToken } from '../fn/publico/refresh-token';
import { RefreshToken$Params } from '../fn/publico/refresh-token';
import { registerCitizen } from '../fn/publico/register-citizen';
import { RegisterCitizen$Params } from '../fn/publico/register-citizen';
import { RegistroUsuarioResponse } from '../models/registro-usuario-response';
import { resetPassword } from '../fn/publico/reset-password';
import { ResetPassword$Params } from '../fn/publico/reset-password';


/**
 * Accesible sin token.
 */
@Injectable({ providedIn: 'root' })
export class PublicoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/login';

  /**
   * Iniciar sesión.
   *
   * Recibe credenciales y devuelve Access Token + Refresh Token. Controles defensivos: rate limiting y bloqueo temporal ante intentos fallidos.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Promise<StrictHttpResponse<AuthResponse>> {
    const obs = login(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Iniciar sesión.
   *
   * Recibe credenciales y devuelve Access Token + Refresh Token. Controles defensivos: rate limiting y bloqueo temporal ante intentos fallidos.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Promise<AuthResponse> {
    const resp = this.login$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuthResponse>): AuthResponse => r.body);
  }

  /** Path part for operation `refreshToken()` */
  static readonly RefreshTokenPath = '/token/refresh';

  /**
   * Renovar tokens (refresh).
   *
   * Canjea un refresh token por un nuevo access token y un nuevo refresh token (rotación). Si el refresh token está revocado, expirado o no corresponde al estado de rotación, se rechaza.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refreshToken()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken$Response(params: RefreshToken$Params, context?: HttpContext): Promise<StrictHttpResponse<AuthResponse>> {
    const obs = refreshToken(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Renovar tokens (refresh).
   *
   * Canjea un refresh token por un nuevo access token y un nuevo refresh token (rotación). Si el refresh token está revocado, expirado o no corresponde al estado de rotación, se rechaza.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refreshToken$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken(params: RefreshToken$Params, context?: HttpContext): Promise<AuthResponse> {
    const resp = this.refreshToken$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuthResponse>): AuthResponse => r.body);
  }

  /** Path part for operation `registerCitizen()` */
  static readonly RegisterCitizenPath = '/register/citizen';

  /**
   * Registro de Ciudadano (Auto-servicio).
   *
   * Crea una cuenta con rol CIUDADANO por defecto. Nota de privacidad: nombre y cédula se tratan como datos sensibles y no se exponen a roles operativos.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerCitizen()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerCitizen$Response(params: RegisterCitizen$Params, context?: HttpContext): Promise<StrictHttpResponse<RegistroUsuarioResponse>> {
    const obs = registerCitizen(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Registro de Ciudadano (Auto-servicio).
   *
   * Crea una cuenta con rol CIUDADANO por defecto. Nota de privacidad: nombre y cédula se tratan como datos sensibles y no se exponen a roles operativos.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerCitizen$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerCitizen(params: RegisterCitizen$Params, context?: HttpContext): Promise<RegistroUsuarioResponse> {
    const resp = this.registerCitizen$Response(params, context);
    return resp.then((r: StrictHttpResponse<RegistroUsuarioResponse>): RegistroUsuarioResponse => r.body);
  }

  /** Path part for operation `forgotPassword()` */
  static readonly ForgotPasswordPath = '/password/forgot';

  /**
   * Solicitar recuperación.
   *
   * Genera token y envía correo (o log en MVP). Para evitar enumeración de cuentas, la respuesta es uniforme: se devuelve 200 aunque el email no exista.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `forgotPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  forgotPassword$Response(params: ForgotPassword$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = forgotPassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Solicitar recuperación.
   *
   * Genera token y envía correo (o log en MVP). Para evitar enumeración de cuentas, la respuesta es uniforme: se devuelve 200 aunque el email no exista.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `forgotPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  forgotPassword(params: ForgotPassword$Params, context?: HttpContext): Promise<void> {
    const resp = this.forgotPassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `resetPassword()` */
  static readonly ResetPasswordPath = '/password/reset';

  /**
   * Establecer nueva contraseña.
   *
   * Usa el token recibido por correo.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword$Response(params: ResetPassword$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = resetPassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Establecer nueva contraseña.
   *
   * Usa el token recibido por correo.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword(params: ResetPassword$Params, context?: HttpContext): Promise<void> {
    const resp = this.resetPassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
