/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { forgot } from '../fn/publico/forgot';
import { Forgot$Params } from '../fn/publico/forgot';
import { logout } from '../fn/publico/logout';
import { Logout$Params } from '../fn/publico/logout';
import { LogoutResponse } from '../models/logout-response';
import { PasswordResetResponse } from '../models/password-reset-response';
import { registrarCiudadano } from '../fn/publico/registrar-ciudadano';
import { RegistrarCiudadano$Params } from '../fn/publico/registrar-ciudadano';
import { RegistroUsuarioResponse } from '../models/registro-usuario-response';
import { reset } from '../fn/publico/reset';
import { Reset$Params } from '../fn/publico/reset';


/**
 * Endpoints accesibles sin token.
 */
@Injectable({ providedIn: 'root' })
export class PublicoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registrarCiudadano()` */
  static readonly RegistrarCiudadanoPath = '/register/citizen';

  /**
   * Registro de Ciudadano (Auto-servicio).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrarCiudadano()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarCiudadano$Response(params: RegistrarCiudadano$Params, context?: HttpContext): Promise<StrictHttpResponse<RegistroUsuarioResponse>> {
    const obs = registrarCiudadano(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Registro de Ciudadano (Auto-servicio).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrarCiudadano$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarCiudadano(params: RegistrarCiudadano$Params, context?: HttpContext): Promise<RegistroUsuarioResponse> {
    const resp = this.registrarCiudadano$Response(params, context);
    return resp.then((r: StrictHttpResponse<RegistroUsuarioResponse>): RegistroUsuarioResponse => r.body);
  }

  /** Path part for operation `forgot()` */
  static readonly ForgotPath = '/password/forgot';

  /**
   * Solicitar recuperación de contraseña.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `forgot()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  forgot$Response(params: Forgot$Params, context?: HttpContext): Promise<StrictHttpResponse<PasswordResetResponse>> {
    const obs = forgot(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Solicitar recuperación de contraseña.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `forgot$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  forgot(params: Forgot$Params, context?: HttpContext): Promise<PasswordResetResponse> {
    const resp = this.forgot$Response(params, context);
    return resp.then((r: StrictHttpResponse<PasswordResetResponse>): PasswordResetResponse => r.body);
  }

  /** Path part for operation `reset()` */
  static readonly ResetPath = '/password/reset';

  /**
   * Establecer nueva contraseña.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reset()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reset$Response(params: Reset$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = reset(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Establecer nueva contraseña.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reset$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reset(params: Reset$Params, context?: HttpContext): Promise<void> {
    const resp = this.reset$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `logout()` */
  static readonly LogoutPath = '/auth/logout';

  /**
   * Cerrar sesión y revocar refresh token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logout()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  logout$Response(params: Logout$Params, context?: HttpContext): Promise<StrictHttpResponse<LogoutResponse>> {
    const obs = logout(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cerrar sesión y revocar refresh token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logout$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  logout(params: Logout$Params, context?: HttpContext): Promise<LogoutResponse> {
    const resp = this.logout$Response(params, context);
    return resp.then((r: StrictHttpResponse<LogoutResponse>): LogoutResponse => r.body);
  }

}
