/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ActualizarAliasRequest } from './models/actualizar-alias-request';
export type { AliasResponse } from './models/alias-response';
export type { AuthResponse } from './models/auth-response';
export type { EntidadEnum } from './models/entidad-enum';
export type { ErrorResponse } from './models/error-response';
export type { LoginRequest } from './models/login-request';
export type { LogoutRequest } from './models/logout-request';
export type { PasswordResetRequest } from './models/password-reset-request';
export type { RefreshTokenRequest } from './models/refresh-token-request';
export type { RegistroCiudadanoRequest } from './models/registro-ciudadano-request';
export type { RegistroStaffRequest } from './models/registro-staff-request';
export type { RegistroUsuarioResponse } from './models/registro-usuario-response';
export type { RolEnum } from './models/rol-enum';
export type { UsuarioPerfilResponse } from './models/usuario-perfil-response';
export type { UsuarioPublicoResponse } from './models/usuario-publico-response';
