/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ErrorResponse } from './models/error-response';
export type { PasswordForgotRequest } from './models/password-forgot-request';
export type { PasswordResetRequest } from './models/password-reset-request';
export type { PasswordResetResponse } from './models/password-reset-response';
export type { RegistroCiudadanoAuthRequest } from './models/registro-ciudadano-auth-request';
export type { RegistroStaffAuthRequest } from './models/registro-staff-auth-request';
export type { RegistroUsuarioResponse } from './models/registro-usuario-response';
