/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActorTypeEnum } from '../../models/actor-type-enum';
import { AuditEventPageResponse } from '../../models/audit-event-page-response';
import { EntityTypeEnum } from '../../models/entity-type-enum';
import { RolEnum } from '../../models/rol-enum';
import { SourceServiceEnum } from '../../models/source-service-enum';

export interface EventosGet$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  page?: number;
  size?: number;

/**
 * Campo de ordenamiento; prefijo '-' para descendente.
 */
  sort?: string;
  entityType?: EntityTypeEnum;
  entityId?: string;
  action?: string;
  sourceService?: SourceServiceEnum;
  actorType?: ActorTypeEnum;
  actorUserId?: number;
  actorRole?: RolEnum;
  correlationId?: string;
  from?: string;
  to?: string;
}

export function eventosGet(http: HttpClient, rootUrl: string, params?: EventosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AuditEventPageResponse>> {
  const rb = new RequestBuilder(rootUrl, eventosGet.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('entityType', params.entityType, {});
    rb.query('entityId', params.entityId, {});
    rb.query('action', params.action, {});
    rb.query('sourceService', params.sourceService, {});
    rb.query('actorType', params.actorType, {});
    rb.query('actorUserId', params.actorUserId, {});
    rb.query('actorRole', params.actorRole, {});
    rb.query('correlationId', params.correlationId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuditEventPageResponse>;
    })
  );
}

eventosGet.PATH = '/eventos';
