/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EvidenciaInternaResponse } from '../../models/evidencia-interna-response';

export interface CrearIntencionDeCarga$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  filename: string;
  contentType: string;
  size: number;
}

export function crearIntencionDeCarga(http: HttpClient, rootUrl: string, params: CrearIntencionDeCarga$Params, context?: HttpContext): Observable<StrictHttpResponse<EvidenciaInternaResponse>> {
  const rb = new RequestBuilder(rootUrl, crearIntencionDeCarga.PATH, 'post');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.query('filename', params.filename, {});
    rb.query('contentType', params.contentType, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EvidenciaInternaResponse>;
    })
  );
}

crearIntencionDeCarga.PATH = '/interno/uploads';
