/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntidadTipoEnum } from '../../models/entidad-tipo-enum';
import { EvidenciaInternaResponse } from '../../models/evidencia-interna-response';

export interface InternoEntidadesTipoEntidadIdEvidenciasGet$Params {
  tipo: EntidadTipoEnum;
  entidadId: number;
  'X-Correlation-Id'?: string;
}

export function internoEntidadesTipoEntidadIdEvidenciasGet(http: HttpClient, rootUrl: string, params: InternoEntidadesTipoEntidadIdEvidenciasGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EvidenciaInternaResponse>>> {
  const rb = new RequestBuilder(rootUrl, internoEntidadesTipoEntidadIdEvidenciasGet.PATH, 'get');
  if (params) {
    rb.path('tipo', params.tipo, {});
    rb.path('entidadId', params.entidadId, {});
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EvidenciaInternaResponse>>;
    })
  );
}

internoEntidadesTipoEntidadIdEvidenciasGet.PATH = '/interno/entidades/{tipo}/{entidadId}/evidencias';
