/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntidadTipoEnum } from '../../models/entidad-tipo-enum';
import { EvidenciaInternaResponse } from '../../models/evidencia-interna-response';

export interface ObtenerEvidencias$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  tipo: EntidadTipoEnum;
  id: number;
}

export function obtenerEvidencias(http: HttpClient, rootUrl: string, params: ObtenerEvidencias$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EvidenciaInternaResponse>>> {
  const rb = new RequestBuilder(rootUrl, obtenerEvidencias.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.path('tipo', params.tipo, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EvidenciaInternaResponse>>;
    })
  );
}

obtenerEvidencias.PATH = '/interno/entidades/{tipo}/{id}/evidencias';
