/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntidadEnum } from '../../models/entidad-enum';
import { UsuarioResponse } from '../../models/usuario-response';

export interface ObtenerOperadoresPorEntidad_1$Params {
  entidad: EntidadEnum;
}

export function obtenerOperadoresPorEntidad_1(http: HttpClient, rootUrl: string, params: ObtenerOperadoresPorEntidad_1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UsuarioResponse>>> {
  const rb = new RequestBuilder(rootUrl, obtenerOperadoresPorEntidad_1.PATH, 'get');
  if (params) {
    rb.query('entidad', params.entidad, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UsuarioResponse>>;
    })
  );
}

obtenerOperadoresPorEntidad_1.PATH = '/interno/usuarios/operadores';
