/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadTipoEnum } from '../models/entidad-tipo-enum';
export interface AdjuntarEvidenciaRequest {
  entidadId: number;
  entidadTipo: EntidadTipoEnum;

  /**
   * Lista de IDs de evidencias. Puede ser vacía pero no nula. Máximo 3.
   */
  evidenciasIds: Array<string>;
  usuarioId?: number;
}
