/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadTipoEnum } from '../models/entidad-tipo-enum';
import { PermisosEvidenciaRequest } from '../models/permisos-evidencia-request';

/**
 * Adjunta evidencias a una entidad de negocio y define permisos. En denuncias, esta operación suele ejecutarse al crear o actualizar la denuncia.
 */
export interface AdjuntarEvidenciasRequest {
  entidadId: number;
  evidenceIds: Array<string>;
  permisos?: PermisosEvidenciaRequest;
  tipoEntidad: EntidadTipoEnum;
}
