/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadTipoEnum } from '../models/entidad-tipo-enum';
export interface AdjuntarEvidenciasResponse {
  correlationId?: string | null;
  entidadId?: number;
  evidenciasAdjuntas?: Array<string>;
  tipoEntidad?: EntidadTipoEnum;
}
