/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Metadatos declarados por el cliente para validar políticas.
 */
export interface ArchivoPreCargaRequest {
  contentType: string;
  nombreArchivo: string;

  /**
   * Hash opcional para validación de integridad (hex).
   */
  sha256?: string | null;
  sizeBytes: number;
}
