/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ComprobanteUpload } from '../models/comprobante-upload';

/**
 * Confirma evidencias subidas. El backend verifica existencia en storage y aplica validaciones.
 */
export interface ConfirmarUploadRequest {
  comprobantes?: Array<ComprobanteUpload> | null;
  evidenceIds: Array<string>;
}
