/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EvidenciaMetadataResponse } from '../models/evidencia-metadata-response';
export interface ConfirmarUploadResponse {
  correlationId?: string | null;
  evidencias?: Array<EvidenciaMetadataResponse>;
}
