/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UploadItemResponse } from '../models/upload-item-response';
export interface CrearUploadResponse {
  correlationId?: string | null;
  expiresAt?: string;
  items?: Array<UploadItemResponse>;
  uploadId?: string;
}
