/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArchivoPreCargaRequest } from '../models/archivo-pre-carga-request';
import { PropositoEvidenciaEnum } from '../models/proposito-evidencia-enum';
import { RestriccionesUploadRequest } from '../models/restricciones-upload-request';

/**
 * Solicita una o varias URLs firmadas para subir archivos. Se recomienda solicitar todas las imágenes en una sola sesión.
 */
export interface CrearUploadRequest {
  archivos: Array<ArchivoPreCargaRequest>;
  proposito: PropositoEvidenciaEnum;
  restricciones?: RestriccionesUploadRequest;
}
