/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadTipoEnum } from './entidad-tipo-enum';

/**
 * Each possible value of `EntidadTipoEnum`
 */
export const ENTIDAD_TIPO_ENUM: EntidadTipoEnum[] = [
  'DENUNCIA',
  'RESOLUCION'
];