/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoEvidenciaEnum } from './estado-evidencia-enum';

/**
 * Each possible value of `EstadoEvidenciaEnum`
 */
export const ESTADO_EVIDENCIA_ENUM: EstadoEvidenciaEnum[] = [
  'PENDIENTE_SUBIDA',
  'SUBIDA',
  'DISPONIBLE',
  'BLOQUEADA'
];