/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * - PENDIENTE_SUBIDA: creada la sesión, aún no se sube. - SUBIDA: storage reporta subida, falta confirmación o post-proceso. - DISPONIBLE: validada y lista para uso (URLs firmadas). - BLOQUEADA: bloqueada por política (p. ej. malware, tipo no permitido).
 */
export type EstadoEvidenciaEnum = 'PENDIENTE_SUBIDA' | 'SUBIDA' | 'DISPONIBLE' | 'BLOQUEADA';

