/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadTipoEnum } from '../models/entidad-tipo-enum';
import { EstadoEvidenciaEnum } from '../models/estado-evidencia-enum';
import { PropositoEvidenciaEnum } from '../models/proposito-evidencia-enum';
export interface EvidenciaInternaResponse {
  contentType?: string;
  createdAt?: string;
  entidadId?: number;
  entidadTipo?: EntidadTipoEnum;
  estado?: EstadoEvidenciaEnum;
  id?: string;
  proposito?: PropositoEvidenciaEnum;
  sizeBytes?: number;
}
