/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModoUrlEnum } from './modo-url-enum';

/**
 * Each possible value of `ModoUrlEnum`
 */
export const MODO_URL_ENUM: ModoUrlEnum[] = [
  'DESCARGA',
  'PREVIEW'
];