/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RolEnum } from '../models/rol-enum';
export interface PermisosEvidenciaRequest {

  /**
   * Roles habilitados para obtener URL firmada.
   */
  allowedRoles?: Array<RolEnum> | null;

  /**
   * Usuarios específicos habilitados (por ejemplo operador asignado).
   */
  allowedUserIds?: Array<number> | null;

  /**
   * Usuario propietario lógico de la evidencia (ciudadano u operador). Si se omite, se conserva el propietario original de la subida.
   */
  ownerUserId?: number | null;
}
