/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropositoEvidenciaEnum } from './proposito-evidencia-enum';

/**
 * Each possible value of `PropositoEvidenciaEnum`
 */
export const PROPOSITO_EVIDENCIA_ENUM: PropositoEvidenciaEnum[] = [
  'CIUDADANO_CREACION',
  'OPERADOR_RESOLUCION'
];