/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Indica el uso previsto: - CIUDADANO_CREACION: evidencia adjunta al registrar una denuncia. - OPERADOR_RESOLUCION: evidencia adjunta por un operador en la resolución.
 */
export type PropositoEvidenciaEnum = 'CIUDADANO_CREACION' | 'OPERADOR_RESOLUCION';

