/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Opcional. Permite al cliente conocer límites; la política real se aplica en el backend.
 */
export interface RestriccionesUploadRequest {
  maxSizeBytes?: number | null;
  tiposPermitidos?: Array<string> | null;
}
