/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RolEnum } from './rol-enum';

/**
 * Each possible value of `RolEnum`
 */
export const ROL_ENUM: RolEnum[] = [
  'ADMIN_PLATAFORMA',
  'SUPERVISOR_DENUNCIAS',
  'JEFE_INTERNO',
  'JEFE_EXTERNO',
  'OPERADOR_INTERNO',
  'OPERADOR_EXTERNO',
  'AUDITOR',
  'CIUDADANO'
];