/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoEvidenciaEnum } from '../models/estado-evidencia-enum';

/**
 * El cliente sube el archivo usando uploadUrl (y headers requeridos) y luego confirma.
 */
export interface UploadItemResponse {
  estado?: EstadoEvidenciaEnum;
  evidenceId?: string;
  method?: string;
  requiredHeaders?: ({
[key: string]: string;
}) | null;
  uploadUrl?: string;
}
