/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModoUrlEnum } from '../models/modo-url-enum';
export interface UrlFirmadaResponse {
  correlationId?: string | null;
  expiresAt?: string;
  modo?: ModoUrlEnum;
  url?: string;
}
