/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearUploadRequest } from '../../models/crear-upload-request';
import { CrearUploadResponse } from '../../models/crear-upload-response';

export interface UploadsPost$Params {

/**
 * Identificador de trazabilidad distribuida (propagado desde gateway).
 */
  'X-Correlation-Id'?: string;
      body: CrearUploadRequest
}

export function uploadsPost(http: HttpClient, rootUrl: string, params: UploadsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CrearUploadResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadsPost.PATH, 'post');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrearUploadResponse>;
    })
  );
}

uploadsPost.PATH = '/uploads';
