/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearNotificacionInternaRequest } from '../../models/crear-notificacion-interna-request';

export interface InternoDispararPost$Params {

/**
 * Identificador de trazabilidad distribuida (propagado desde gateway).
 */
  'X-Correlation-Id'?: string;
      body: CrearNotificacionInternaRequest
}

export function internoDispararPost(http: HttpClient, rootUrl: string, params: InternoDispararPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, internoDispararPost.PATH, 'post');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

internoDispararPost.PATH = '/interno/disparar';
