/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioResponse } from '../../models/usuario-response';

export interface ObtenerPerfil$Params {
}

export function obtenerPerfil(http: HttpClient, rootUrl: string, params?: ObtenerPerfil$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerPerfil.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponse>;
    })
  );
}

obtenerPerfil.PATH = '/usuarios/me';
