/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntityTypeEnum } from '../../models/entity-type-enum';
import { IntegrityCheckResponse } from '../../models/integrity-check-response';

export interface IntegridadVerificarGet$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  from?: string;
  to?: string;
  entityType?: EntityTypeEnum;
  entityId?: string;

/**
 * Límite de eventos a escanear para proteger el sistema.
 */
  maxScan?: number;
}

export function integridadVerificarGet(http: HttpClient, rootUrl: string, params?: IntegridadVerificarGet$Params, context?: HttpContext): Observable<StrictHttpResponse<IntegrityCheckResponse>> {
  const rb = new RequestBuilder(rootUrl, integridadVerificarGet.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('entityType', params.entityType, {});
    rb.query('entityId', params.entityId, {});
    rb.query('maxScan', params.maxScan, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IntegrityCheckResponse>;
    })
  );
}

integridadVerificarGet.PATH = '/integridad/verificar';
