/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustodyChainResponse } from '../../models/custody-chain-response';

export interface CustodiaEvidenciasEvidenceIdGet$Params {

/**
 * Identificador de trazabilidad distribuida.
 */
  'X-Correlation-Id'?: string;
  evidenceId: string;
  includeIntegrity?: boolean;
}

export function custodiaEvidenciasEvidenceIdGet(http: HttpClient, rootUrl: string, params: CustodiaEvidenciasEvidenceIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CustodyChainResponse>> {
  const rb = new RequestBuilder(rootUrl, custodiaEvidenciasEvidenceIdGet.PATH, 'get');
  if (params) {
    rb.header('X-Correlation-Id', params['X-Correlation-Id'], {});
    rb.path('evidenceId', params.evidenceId, {});
    rb.query('includeIntegrity', params.includeIntegrity, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustodyChainResponse>;
    })
  );
}

custodiaEvidenciasEvidenceIdGet.PATH = '/custodia/evidencias/{evidenceId}';
