/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorTypeEnum } from '../models/actor-type-enum';
import { RolEnum } from '../models/rol-enum';
export interface ActorRef {

  /**
   * Alias público si aplica (evitar nombre real).
   */
  actorAliasPublico?: string | null;
  actorRole?: RolEnum;

  /**
   * Solo si actorType=SERVICE (nombre lógico del servicio).
   */
  actorService?: string | null;
  actorType?: ActorTypeEnum;

  /**
   * Solo si actorType=USER.
   */
  actorUserId?: number | null;
}
