/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorTypeEnum } from './actor-type-enum';

/**
 * Each possible value of `ActorTypeEnum`
 */
export const ACTOR_TYPE_ENUM: ActorTypeEnum[] = [
  'USER',
  'SERVICE',
  'SYSTEM'
];