/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditAcceptedResponse {
  auditId?: string;
  correlationId?: string | null;
  eventId?: string;
  message?: string;
}
