/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorRef } from '../models/actor-ref';
import { EntityTypeEnum } from '../models/entity-type-enum';
import { HashAlgorithmEnum } from '../models/hash-algorithm-enum';
import { SourceServiceEnum } from '../models/source-service-enum';
export interface AuditEventBase {

  /**
   * Acción auditada (string controlado por el emisor, recomendado en mayúsculas con guiones bajos).
   */
  action?: string;
  actor?: ActorRef;
  correlationId?: string | null;
  entityId?: string;
  entityType?: EntityTypeEnum;

  /**
   * Identificador idempotente emitido por el servicio origen.
   */
  eventId?: string;

  /**
   * Hash del evento actual (calculado por el servicio).
   */
  hash?: string;
  hashAlgorithm?: HashAlgorithmEnum;
  id?: string;

  /**
   * Metadatos no sensibles. Evitar PII. Preferir IDs, estados, roles, códigos y detalles neutrales.
   */
  metadata?: {
[key: string]: any;
};
  occurredAt?: string;

  /**
   * Hash del evento inmediatamente anterior dentro de la misma partición lógica.
   */
  prevHash?: string | null;
  receivedAt?: string;
  sourceService?: SourceServiceEnum;
}
