/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorRef } from '../models/actor-ref';
import { EntityTypeEnum } from '../models/entity-type-enum';
import { SourceServiceEnum } from '../models/source-service-enum';
export interface AuditIngestRequest {
  action: string;
  actor: ActorRef;
  correlationId?: string | null;

  /**
   * Identificador canónico recomendado - "{TIPO}:{ID}" (ej. "DENUNCIA:101").
   */
  entityId: string;
  entityType: EntityTypeEnum;

  /**
   * Identificador idempotente emitido por el servicio origen (UUID recomendado).
   */
  eventId: string;

  /**
   * Metadatos no sensibles. Evitar PII.
   */
  metadata?: ({
[key: string]: any;
}) | null;
  occurredAt: string;
  sourceService: SourceServiceEnum;
}
