/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditEventResponse } from '../models/audit-event-response';
export interface AuditEventPageResponse {
  items?: Array<AuditEventResponse>;
  page?: number;
  size?: number;
  totalItems?: number;
  totalPages?: number;
}
