/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditEventResponse } from '../models/audit-event-response';
export interface CustodyChainResponse {
  evidenceId?: string;

  /**
   * Eventos relevantes de custodia filtrados desde el log.
   */
  items?: Array<AuditEventResponse>;
}
