/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditEventResponse } from '../models/audit-event-response';
import { EntityTypeEnum } from '../models/entity-type-enum';
export interface EntityTraceResponse {
  entityId?: string;
  entityType?: EntityTypeEnum;
  items?: Array<AuditEventResponse>;
}
