/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityTypeEnum } from './entity-type-enum';

/**
 * Each possible value of `EntityTypeEnum`
 */
export const ENTITY_TYPE_ENUM: EntityTypeEnum[] = [
  'DENUNCIA',
  'EVIDENCIA',
  'USUARIO',
  'NOTIFICACION',
  'OTRO'
];