/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ErrorResponse {

  /**
   * Identificador de trazabilidad distribuida.
   */
  correlationId?: string;
  error?: string;
  message?: string;
  path?: string;
  status?: number;
  timestamp?: string;
}
