/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HashAlgorithmEnum } from './hash-algorithm-enum';

/**
 * Each possible value of `HashAlgorithmEnum`
 */
export const HASH_ALGORITHM_ENUM: HashAlgorithmEnum[] = [
  'SHA-256'
];