/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IntegrityStatusEnum } from './integrity-status-enum';

/**
 * Each possible value of `IntegrityStatusEnum`
 */
export const INTEGRITY_STATUS_ENUM: IntegrityStatusEnum[] = [
  'OK',
  'INCONSISTENTE',
  'PARCIAL'
];