/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IntegrityStatusEnum } from '../models/integrity-status-enum';
export interface IntegrityCheckResponse {
  firstInconsistentEventId?: string | null;
  from?: string | null;
  message?: string;
  scannedEvents?: number;
  status?: IntegrityStatusEnum;
  to?: string | null;
}
