/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type RolEnum = 'ADMIN_PLATAFORMA' | 'SUPERVISOR_DENUNCIAS' | 'JEFE_INTERNO' | 'JEFE_EXTERNO' | 'OPERADOR_INTERNO' | 'OPERADOR_EXTERNO' | 'AUDITOR' | 'CIUDADANO';

