/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SourceServiceEnum } from './source-service-enum';

/**
 * Each possible value of `SourceServiceEnum`
 */
export const SOURCE_SERVICE_ENUM: SourceServiceEnum[] = [
  'AUTH',
  'DENUNCIAS',
  'NOTIFICACIONES',
  'EVIDENCIAS',
  'GATEWAY',
  'OTRO'
];