/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuditEventPageResponse } from '../models/audit-event-page-response';
import { AuditEventResponse } from '../models/audit-event-response';
import { eventosGet } from '../fn/consultas/eventos-get';
import { EventosGet$Params } from '../fn/consultas/eventos-get';
import { eventosIdGet } from '../fn/consultas/eventos-id-get';
import { EventosIdGet$Params } from '../fn/consultas/eventos-id-get';


/**
 * Consultas de eventos para auditoría (Auditor/Admin; acceso según rol).
 */
@Injectable({ providedIn: 'root' })
export class ConsultasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `eventosGet()` */
  static readonly EventosGetPath = '/eventos';

  /**
   * Buscar eventos de auditoría.
   *
   * Devuelve eventos según filtros. Restringido a roles autorizados (AUDITOR, ADMIN_PLATAFORMA; opcional SUPERVISOR_DENUNCIAS). No retorna PII; el campo metadata debe ser seguro y controlado por el emisor.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `eventosGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  eventosGet$Response(params?: EventosGet$Params, context?: HttpContext): Promise<StrictHttpResponse<AuditEventPageResponse>> {
    const obs = eventosGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Buscar eventos de auditoría.
   *
   * Devuelve eventos según filtros. Restringido a roles autorizados (AUDITOR, ADMIN_PLATAFORMA; opcional SUPERVISOR_DENUNCIAS). No retorna PII; el campo metadata debe ser seguro y controlado por el emisor.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `eventosGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  eventosGet(params?: EventosGet$Params, context?: HttpContext): Promise<AuditEventPageResponse> {
    const resp = this.eventosGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuditEventPageResponse>): AuditEventPageResponse => r.body);
  }

  /** Path part for operation `eventosIdGet()` */
  static readonly EventosIdGetPath = '/eventos/{id}';

  /**
   * Obtener un evento de auditoría.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `eventosIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  eventosIdGet$Response(params: EventosIdGet$Params, context?: HttpContext): Promise<StrictHttpResponse<AuditEventResponse>> {
    const obs = eventosIdGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener un evento de auditoría.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `eventosIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  eventosIdGet(params: EventosIdGet$Params, context?: HttpContext): Promise<AuditEventResponse> {
    const resp = this.eventosIdGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuditEventResponse>): AuditEventResponse => r.body);
  }

}
