/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { integridadVerificarGet } from '../fn/integridad/integridad-verificar-get';
import { IntegridadVerificarGet$Params } from '../fn/integridad/integridad-verificar-get';
import { IntegrityCheckResponse } from '../models/integrity-check-response';


/**
 * Verificación de integridad de la cadena hash.
 */
@Injectable({ providedIn: 'root' })
export class IntegridadService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `integridadVerificarGet()` */
  static readonly IntegridadVerificarGetPath = '/integridad/verificar';

  /**
   * Verificar integridad de la cadena hash.
   *
   * Verifica continuidad hash (prevHash -> hash) en un rango de tiempo o por entityType/entityId. Retorna un resultado con estado, primer evento inconsistente (si aplica) y métricas básicas.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `integridadVerificarGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  integridadVerificarGet$Response(params?: IntegridadVerificarGet$Params, context?: HttpContext): Promise<StrictHttpResponse<IntegrityCheckResponse>> {
    const obs = integridadVerificarGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Verificar integridad de la cadena hash.
   *
   * Verifica continuidad hash (prevHash -> hash) en un rango de tiempo o por entityType/entityId. Retorna un resultado con estado, primer evento inconsistente (si aplica) y métricas básicas.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `integridadVerificarGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  integridadVerificarGet(params?: IntegridadVerificarGet$Params, context?: HttpContext): Promise<IntegrityCheckResponse> {
    const resp = this.integridadVerificarGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<IntegrityCheckResponse>): IntegrityCheckResponse => r.body);
  }

}
