/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuditAcceptedResponse } from '../models/audit-accepted-response';
import { internoEventosPost } from '../fn/interno/interno-eventos-post';
import { InternoEventosPost$Params } from '../fn/interno/interno-eventos-post';


/**
 * Endpoints S2S para ingestión de eventos desde otros microservicios.
 */
@Injectable({ providedIn: 'root' })
export class InternoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `internoEventosPost()` */
  static readonly InternoEventosPostPath = '/interno/eventos';

  /**
   * Ingerir evento de auditoría (S2S).
   *
   * Endpoint S2S para que otros microservicios registren eventos. Reglas: - Idempotencia por eventId (reintentos no deben duplicar). - El servicio calcula hash y encadena prevHash automáticamente. - metadata debe evitar PII; se recomienda usar IDs y campos neutrales.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `internoEventosPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internoEventosPost$Response(params: InternoEventosPost$Params, context?: HttpContext): Promise<StrictHttpResponse<AuditAcceptedResponse>> {
    const obs = internoEventosPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Ingerir evento de auditoría (S2S).
   *
   * Endpoint S2S para que otros microservicios registren eventos. Reglas: - Idempotencia por eventId (reintentos no deben duplicar). - El servicio calcula hash y encadena prevHash automáticamente. - metadata debe evitar PII; se recomienda usar IDs y campos neutrales.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `internoEventosPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internoEventosPost(params: InternoEventosPost$Params, context?: HttpContext): Promise<AuditAcceptedResponse> {
    const resp = this.internoEventosPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuditAcceptedResponse>): AuditAcceptedResponse => r.body);
  }

}
