/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { custodiaEvidenciasEvidenceIdGet } from '../fn/trazas/custodia-evidencias-evidence-id-get';
import { CustodiaEvidenciasEvidenceIdGet$Params } from '../fn/trazas/custodia-evidencias-evidence-id-get';
import { CustodyChainResponse } from '../models/custody-chain-response';
import { EntityTraceResponse } from '../models/entity-trace-response';
import { trazasEntityTypeEntityIdGet } from '../fn/trazas/trazas-entity-type-entity-id-get';
import { TrazasEntityTypeEntityIdGet$Params } from '../fn/trazas/trazas-entity-type-entity-id-get';


/**
 * Consultas por entidad de negocio (denuncias, evidencias, usuarios).
 */
@Injectable({ providedIn: 'root' })
export class TrazasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `trazasEntityTypeEntityIdGet()` */
  static readonly TrazasEntityTypeEntityIdGetPath = '/trazas/{entityType}/{entityId}';

  /**
   * Obtener traza completa por entidad.
   *
   * Devuelve la secuencia de eventos asociada a una entidad (por ejemplo, una denuncia o evidencia), ordenada por fecha de ocurrencia. Útil para auditoría de proceso y transparencia.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `trazasEntityTypeEntityIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  trazasEntityTypeEntityIdGet$Response(params: TrazasEntityTypeEntityIdGet$Params, context?: HttpContext): Promise<StrictHttpResponse<EntityTraceResponse>> {
    const obs = trazasEntityTypeEntityIdGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener traza completa por entidad.
   *
   * Devuelve la secuencia de eventos asociada a una entidad (por ejemplo, una denuncia o evidencia), ordenada por fecha de ocurrencia. Útil para auditoría de proceso y transparencia.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `trazasEntityTypeEntityIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  trazasEntityTypeEntityIdGet(params: TrazasEntityTypeEntityIdGet$Params, context?: HttpContext): Promise<EntityTraceResponse> {
    const resp = this.trazasEntityTypeEntityIdGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<EntityTraceResponse>): EntityTraceResponse => r.body);
  }

  /** Path part for operation `custodiaEvidenciasEvidenceIdGet()` */
  static readonly CustodiaEvidenciasEvidenceIdGetPath = '/custodia/evidencias/{evidenceId}';

  /**
   * Obtener cadena de custodia de una evidencia.
   *
   * Devuelve eventos relevantes de custodia para una evidencia: creación de pre-carga, confirmación, adjunto a denuncia, emisiones de URL firmada, etc. Diseñado para el rol AUDITOR.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `custodiaEvidenciasEvidenceIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  custodiaEvidenciasEvidenceIdGet$Response(params: CustodiaEvidenciasEvidenceIdGet$Params, context?: HttpContext): Promise<StrictHttpResponse<CustodyChainResponse>> {
    const obs = custodiaEvidenciasEvidenceIdGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener cadena de custodia de una evidencia.
   *
   * Devuelve eventos relevantes de custodia para una evidencia: creación de pre-carga, confirmación, adjunto a denuncia, emisiones de URL firmada, etc. Diseñado para el rol AUDITOR.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `custodiaEvidenciasEvidenceIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  custodiaEvidenciasEvidenceIdGet(params: CustodiaEvidenciasEvidenceIdGet$Params, context?: HttpContext): Promise<CustodyChainResponse> {
    const resp = this.custodiaEvidenciasEvidenceIdGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<CustodyChainResponse>): CustodyChainResponse => r.body);
  }

}
