/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CrearDenuncia$Params as CrearDenuncia$Params } from './fn/ciudadano/crear-denuncia';
export { crearDenuncia as crearDenuncia } from './fn/ciudadano/crear-denuncia';
export type { DenunciasMeGet$Params as DenunciasMeGet$Params } from './fn/ciudadano/denuncias-me-get';
export { denunciasMeGet as denunciasMeGet } from './fn/ciudadano/denuncias-me-get';
export type { DenunciasGestionGet$Params as DenunciasGestionGet$Params } from './fn/gestion-interna/denuncias-gestion-get';
export { denunciasGestionGet as denunciasGestionGet } from './fn/gestion-interna/denuncias-gestion-get';
export type { DenunciasIdAsignacionPost$Params as DenunciasIdAsignacionPost$Params } from './fn/gestion-interna/denuncias-id-asignacion-post';
export { denunciasIdAsignacionPost as denunciasIdAsignacionPost } from './fn/gestion-interna/denuncias-id-asignacion-post';
export type { DenunciasIdResolucionPatch$Params as DenunciasIdResolucionPatch$Params } from './fn/gestion-interna/denuncias-id-resolucion-patch';
export { denunciasIdResolucionPatch as denunciasIdResolucionPatch } from './fn/gestion-interna/denuncias-id-resolucion-patch';
export type { DenunciasIdValidacionPatch$Params as DenunciasIdValidacionPatch$Params } from './fn/gestion-interna/denuncias-id-validacion-patch';
export { denunciasIdValidacionPatch as denunciasIdValidacionPatch } from './fn/gestion-interna/denuncias-id-validacion-patch';
