/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ListarDenuncias$Params as ListarDenuncias$Params } from './fn/denuncias/listar-denuncias';
export { listarDenuncias as listarDenuncias } from './fn/denuncias/listar-denuncias';
export type { CrearDenuncia$Params as CrearDenuncia$Params } from './fn/denuncias/crear-denuncia';
export { crearDenuncia as crearDenuncia } from './fn/denuncias/crear-denuncia';
export type { ObtenerDenunciaPorId$Params as ObtenerDenunciaPorId$Params } from './fn/denuncias/obtener-denuncia-por-id';
export { obtenerDenunciaPorId as obtenerDenunciaPorId } from './fn/denuncias/obtener-denuncia-por-id';
export type { AsignarEntidadADenuncia$Params as AsignarEntidadADenuncia$Params } from './fn/workflow/asignar-entidad-a-denuncia';
export { asignarEntidadADenuncia as asignarEntidadADenuncia } from './fn/workflow/asignar-entidad-a-denuncia';
export type { AsignarOperadorAdenuncia$Params as AsignarOperadorAdenuncia$Params } from './fn/workflow/asignar-operador-adenuncia';
export { asignarOperadorAdenuncia as asignarOperadorAdenuncia } from './fn/workflow/asignar-operador-adenuncia';
export type { IniciarProcesoDenunciaOperadores$Params as IniciarProcesoDenunciaOperadores$Params } from './fn/workflow/iniciar-proceso-denuncia-operadores';
export { iniciarProcesoDenunciaOperadores as iniciarProcesoDenunciaOperadores } from './fn/workflow/iniciar-proceso-denuncia-operadores';
export type { ResolverDenuncia$Params as ResolverDenuncia$Params } from './fn/workflow/resolver-denuncia';
export { resolverDenuncia as resolverDenuncia } from './fn/workflow/resolver-denuncia';
export type { ValidarSolucionDenuncia$Params as ValidarSolucionDenuncia$Params } from './fn/workflow/validar-solucion-denuncia';
export { validarSolucionDenuncia as validarSolucionDenuncia } from './fn/workflow/validar-solucion-denuncia';
export type { DenunciaHistorialEstados$Params as DenunciaHistorialEstados$Params } from './fn/workflow/denuncia-historial-estados';
export { denunciaHistorialEstados as denunciaHistorialEstados } from './fn/workflow/denuncia-historial-estados';
