/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AsignarOperadorRequest } from './models/asignar-operador-request';
export type { CategoriaDenunciaEnum } from './models/categoria-denuncia-enum';
export type { CrearDenunciaRequest } from './models/crear-denuncia-request';
export type { DenunciaEstadoHistorialResponse } from './models/denuncia-estado-historial-response';
export type { DenunciaListadoResponse } from './models/denuncia-listado-response';
export type { DenunciaResponse } from './models/denuncia-response';
export type { DenunciaResumenResponse } from './models/denuncia-resumen-response';
export type { EntidadResponsableEnum } from './models/entidad-responsable-enum';
export type { ErrorResponse } from './models/error-response';
export type { EstadoCambio } from './models/estado-cambio';
export type { EstadoDenunciaEnum } from './models/estado-denuncia-enum';
export type { EvidenciaDto } from './models/evidencia-dto';
export type { MarcarResolucionRequest } from './models/marcar-resolucion-request';
export type { NivelAnonimatoEnum } from './models/nivel-anonimato-enum';
export type { RechazarDenunciaRequest } from './models/rechazar-denuncia-request';
export type { ValidarSolucionRequest } from './models/validar-solucion-request';
