/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoriaEnum } from './models/categoria-enum';
export type { CrearDenunciaRequest } from './models/crear-denuncia-request';
export type { DenunciaCitizenViewResponse } from './models/denuncia-citizen-view-response';
export type { DenunciaResumenResponse } from './models/denuncia-resumen-response';
export type { DenunciaStaffViewResponse } from './models/denuncia-staff-view-response';
export type { ErrorResponse } from './models/error-response';
export type { EstadoDenunciaEnum } from './models/estado-denuncia-enum';
export type { EvidenceId } from './models/evidence-id';
export type { NivelAnonimatoEnum } from './models/nivel-anonimato-enum';
