/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CiudadanoService } from './services/ciudadano.service';
export { GestionInternaService } from './services/gestion-interna.service';
