/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { DenunciasService } from './services/denuncias.service';
export { WorkflowService } from './services/workflow.service';
