/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasswordForgotRequest } from '../../models/password-forgot-request';
import { PasswordResetResponse } from '../../models/password-reset-response';

export interface Forgot$Params {
      body: PasswordForgotRequest
}

export function forgot(http: HttpClient, rootUrl: string, params: Forgot$Params, context?: HttpContext): Observable<StrictHttpResponse<PasswordResetResponse>> {
  const rb = new RequestBuilder(rootUrl, forgot.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PasswordResetResponse>;
    })
  );
}

forgot.PATH = '/password/forgot';
