/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActualizarAliasRequest } from '../../models/actualizar-alias-request';
import { AliasResponse } from '../../models/alias-response';

export interface ActualizarAlias$Params {
  id: number;
      body: ActualizarAliasRequest
}

export function actualizarAlias(http: HttpClient, rootUrl: string, params: ActualizarAlias$Params, context?: HttpContext): Observable<StrictHttpResponse<AliasResponse>> {
  const rb = new RequestBuilder(rootUrl, actualizarAlias.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AliasResponse>;
    })
  );
}

actualizarAlias.PATH = '/interno/usuarios/{id}/alias';
