/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistroStaffRequest } from '../../models/registro-staff-request';
import { UsuarioResponse } from '../../models/usuario-response';

export interface CrearStaff$Params {
      body: RegistroStaffRequest
}

export function crearStaff(http: HttpClient, rootUrl: string, params: CrearStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, crearStaff.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponse>;
    })
  );
}

crearStaff.PATH = '/interno/usuarios/staff';
