/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioPublicoResponse } from '../../models/usuario-publico-response';

export interface ObtenerPublico$Params {
  id: number;
}

export function obtenerPublico(http: HttpClient, rootUrl: string, params: ObtenerPublico$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioPublicoResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerPublico.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioPublicoResponse>;
    })
  );
}

obtenerPublico.PATH = '/interno/usuarios/{id}/publico';
