/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CrearNotificacionInternaRequest } from './models/crear-notificacion-interna-request';
export type { NotificacionResponse } from './models/notificacion-response';
export type { PrioridadEnum } from './models/prioridad-enum';
export type { TipoEventoEnum } from './models/tipo-evento-enum';
