/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { usuarioAdminObtenerJefePorEntidad } from '../fn/admin/usuario-admin-obtener-jefe-por-entidad';
import { UsuarioAdminObtenerJefePorEntidad$Params } from '../fn/admin/usuario-admin-obtener-jefe-por-entidad';
import { usuarioAdminObtenerOperadoresPorEntidad } from '../fn/admin/usuario-admin-obtener-operadores-por-entidad';
import { UsuarioAdminObtenerOperadoresPorEntidad$Params } from '../fn/admin/usuario-admin-obtener-operadores-por-entidad';
import { UsuarioResponse } from '../models/usuario-response';


/**
 * Endpoints de administración con roles (SUPERVISOR, ADMIN)
 */
@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `usuarioAdminObtenerJefePorEntidad()` */
  static readonly UsuarioAdminObtenerJefePorEntidadPath = '/usuarios/jefe';

  /**
   * Obtener jefe por entidad.
   *
   * Requiere roles SUPERVISOR o ADMIN
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usuarioAdminObtenerJefePorEntidad()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioAdminObtenerJefePorEntidad$Response(params: UsuarioAdminObtenerJefePorEntidad$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = usuarioAdminObtenerJefePorEntidad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener jefe por entidad.
   *
   * Requiere roles SUPERVISOR o ADMIN
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usuarioAdminObtenerJefePorEntidad$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioAdminObtenerJefePorEntidad(params: UsuarioAdminObtenerJefePorEntidad$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.usuarioAdminObtenerJefePorEntidad$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `usuarioAdminObtenerOperadoresPorEntidad()` */
  static readonly UsuarioAdminObtenerOperadoresPorEntidadPath = '/usuarios/operadores';

  /**
   * Obtener operadores por entidad.
   *
   * Requiere roles SUPERVISOR o ADMIN
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usuarioAdminObtenerOperadoresPorEntidad()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioAdminObtenerOperadoresPorEntidad$Response(params: UsuarioAdminObtenerOperadoresPorEntidad$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioResponse>>> {
    const obs = usuarioAdminObtenerOperadoresPorEntidad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener operadores por entidad.
   *
   * Requiere roles SUPERVISOR o ADMIN
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usuarioAdminObtenerOperadoresPorEntidad$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioAdminObtenerOperadoresPorEntidad(params: UsuarioAdminObtenerOperadoresPorEntidad$Params, context?: HttpContext): Promise<Array<UsuarioResponse>> {
    const resp = this.usuarioAdminObtenerOperadoresPorEntidad$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioResponse>>): Array<UsuarioResponse> => r.body);
  }

}
