/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { actualizarAlias } from '../fn/operations/actualizar-alias';
import { ActualizarAlias$Params } from '../fn/operations/actualizar-alias';
import { AliasResponse } from '../models/alias-response';
import { crearCiudadano } from '../fn/operations/crear-ciudadano';
import { CrearCiudadano$Params } from '../fn/operations/crear-ciudadano';
import { crearStaff } from '../fn/operations/crear-staff';
import { CrearStaff$Params } from '../fn/operations/crear-staff';
import { obtenerJefePorEntidad } from '../fn/operations/obtener-jefe-por-entidad';
import { obtenerJefePorEntidad_1 } from '../fn/operations/obtener-jefe-por-entidad-1';
import { ObtenerJefePorEntidad_1$Params } from '../fn/operations/obtener-jefe-por-entidad-1';
import { ObtenerJefePorEntidad$Params } from '../fn/operations/obtener-jefe-por-entidad';
import { obtenerOperadoresPorEntidad } from '../fn/operations/obtener-operadores-por-entidad';
import { obtenerOperadoresPorEntidad_1 } from '../fn/operations/obtener-operadores-por-entidad-1';
import { ObtenerOperadoresPorEntidad_1$Params } from '../fn/operations/obtener-operadores-por-entidad-1';
import { ObtenerOperadoresPorEntidad$Params } from '../fn/operations/obtener-operadores-por-entidad';
import { obtenerPorCedula } from '../fn/operations/obtener-por-cedula';
import { ObtenerPorCedula$Params } from '../fn/operations/obtener-por-cedula';
import { obtenerPublico } from '../fn/operations/obtener-publico';
import { ObtenerPublico$Params } from '../fn/operations/obtener-publico';
import { obtenerUsuario } from '../fn/operations/obtener-usuario';
import { ObtenerUsuario$Params } from '../fn/operations/obtener-usuario';
import { UsuarioPublicoResponse } from '../models/usuario-publico-response';
import { UsuarioResponse } from '../models/usuario-response';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `obtenerJefePorEntidad()` */
  static readonly ObtenerJefePorEntidadPath = '/usuarios/jefe';

  /**
   * Obtener jefe por entidad.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerJefePorEntidad()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerJefePorEntidad$Response(params: ObtenerJefePorEntidad$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = obtenerJefePorEntidad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener jefe por entidad.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerJefePorEntidad$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerJefePorEntidad(params: ObtenerJefePorEntidad$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.obtenerJefePorEntidad$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerOperadoresPorEntidad()` */
  static readonly ObtenerOperadoresPorEntidadPath = '/usuarios/operadores';

  /**
   * Obtener operadores por entidad.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerOperadoresPorEntidad()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerOperadoresPorEntidad$Response(params: ObtenerOperadoresPorEntidad$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioResponse>>> {
    const obs = obtenerOperadoresPorEntidad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener operadores por entidad.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerOperadoresPorEntidad$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerOperadoresPorEntidad(params: ObtenerOperadoresPorEntidad$Params, context?: HttpContext): Promise<Array<UsuarioResponse>> {
    const resp = this.obtenerOperadoresPorEntidad$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioResponse>>): Array<UsuarioResponse> => r.body);
  }

  /** Path part for operation `crearCiudadano()` */
  static readonly CrearCiudadanoPath = '/interno/usuarios/ciudadano';

  /**
   * Crear ciudadano.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearCiudadano()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearCiudadano$Response(params: CrearCiudadano$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = crearCiudadano(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear ciudadano.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearCiudadano$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearCiudadano(params: CrearCiudadano$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.crearCiudadano$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `crearStaff()` */
  static readonly CrearStaffPath = '/interno/usuarios/staff';

  /**
   * Crear staff.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearStaff()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearStaff$Response(params: CrearStaff$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = crearStaff(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear staff.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearStaff$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearStaff(params: CrearStaff$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.crearStaff$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerUsuario()` */
  static readonly ObtenerUsuarioPath = '/interno/usuarios/{id}';

  /**
   * Obtener usuario por id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerUsuario()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerUsuario$Response(params: ObtenerUsuario$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = obtenerUsuario(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener usuario por id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerUsuario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerUsuario(params: ObtenerUsuario$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.obtenerUsuario$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerPorCedula()` */
  static readonly ObtenerPorCedulaPath = '/interno/usuarios/cedula/{cedula}';

  /**
   * Obtener usuario por cedula.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerPorCedula()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPorCedula$Response(params: ObtenerPorCedula$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = obtenerPorCedula(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener usuario por cedula.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerPorCedula$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPorCedula(params: ObtenerPorCedula$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.obtenerPorCedula$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerPublico()` */
  static readonly ObtenerPublicoPath = '/interno/usuarios/{id}/publico';

  /**
   * Obtener vista pública de usuario.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerPublico()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPublico$Response(params: ObtenerPublico$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioPublicoResponse>> {
    const obs = obtenerPublico(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener vista pública de usuario.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerPublico$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPublico(params: ObtenerPublico$Params, context?: HttpContext): Promise<UsuarioPublicoResponse> {
    const resp = this.obtenerPublico$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioPublicoResponse>): UsuarioPublicoResponse => r.body);
  }

  /** Path part for operation `actualizarAlias()` */
  static readonly ActualizarAliasPath = '/interno/usuarios/{id}/alias';

  /**
   * Actualizar alias público.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `actualizarAlias()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  actualizarAlias$Response(params: ActualizarAlias$Params, context?: HttpContext): Promise<StrictHttpResponse<AliasResponse>> {
    const obs = actualizarAlias(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Actualizar alias público.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `actualizarAlias$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  actualizarAlias(params: ActualizarAlias$Params, context?: HttpContext): Promise<AliasResponse> {
    const resp = this.actualizarAlias$Response(params, context);
    return resp.then((r: StrictHttpResponse<AliasResponse>): AliasResponse => r.body);
  }

  /** Path part for operation `obtenerJefePorEntidad_1()` */
  static readonly ObtenerJefePorEntidad_1Path = '/interno/usuarios/jefe';

  /**
   * Obtener jefe por entidad (interno).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerJefePorEntidad_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerJefePorEntidad_1$Response(params: ObtenerJefePorEntidad_1$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = obtenerJefePorEntidad_1(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener jefe por entidad (interno).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerJefePorEntidad_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerJefePorEntidad_1(params: ObtenerJefePorEntidad_1$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.obtenerJefePorEntidad_1$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerOperadoresPorEntidad_1()` */
  static readonly ObtenerOperadoresPorEntidad_1Path = '/interno/usuarios/operadores';

  /**
   * Obtener operadores por entidad (interno).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerOperadoresPorEntidad_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerOperadoresPorEntidad_1$Response(params: ObtenerOperadoresPorEntidad_1$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioResponse>>> {
    const obs = obtenerOperadoresPorEntidad_1(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener operadores por entidad (interno).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerOperadoresPorEntidad_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerOperadoresPorEntidad_1(params: ObtenerOperadoresPorEntidad_1$Params, context?: HttpContext): Promise<Array<UsuarioResponse>> {
    const resp = this.obtenerOperadoresPorEntidad_1$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioResponse>>): Array<UsuarioResponse> => r.body);
  }

}
