/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { actualizarAlias } from '../fn/interno/actualizar-alias';
import { ActualizarAlias$Params } from '../fn/interno/actualizar-alias';
import { AliasResponse } from '../models/alias-response';
import { crearCiudadano } from '../fn/interno/crear-ciudadano';
import { CrearCiudadano$Params } from '../fn/interno/crear-ciudadano';
import { crearStaff } from '../fn/interno/crear-staff';
import { CrearStaff$Params } from '../fn/interno/crear-staff';
import { obtenerPorCedula } from '../fn/interno/obtener-por-cedula';
import { ObtenerPorCedula$Params } from '../fn/interno/obtener-por-cedula';
import { obtenerPublico } from '../fn/interno/obtener-publico';
import { ObtenerPublico$Params } from '../fn/interno/obtener-publico';
import { obtenerUsuario } from '../fn/interno/obtener-usuario';
import { ObtenerUsuario$Params } from '../fn/interno/obtener-usuario';
import { usuarioInternoObtenerJefePorEntidad } from '../fn/interno/usuario-interno-obtener-jefe-por-entidad';
import { UsuarioInternoObtenerJefePorEntidad$Params } from '../fn/interno/usuario-interno-obtener-jefe-por-entidad';
import { usuarioInternoObtenerOperadoresPorEntidad } from '../fn/interno/usuario-interno-obtener-operadores-por-entidad';
import { UsuarioInternoObtenerOperadoresPorEntidad$Params } from '../fn/interno/usuario-interno-obtener-operadores-por-entidad';
import { UsuarioPublicoResponse } from '../models/usuario-publico-response';
import { UsuarioResponse } from '../models/usuario-response';


/**
 * Endpoints internos del servicio (sin control de rol en código)
 */
@Injectable({ providedIn: 'root' })
export class InternoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `crearCiudadano()` */
  static readonly CrearCiudadanoPath = '/interno/usuarios/ciudadano';

  /**
   * Crear ciudadano.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearCiudadano()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearCiudadano$Response(params: CrearCiudadano$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = crearCiudadano(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear ciudadano.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearCiudadano$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearCiudadano(params: CrearCiudadano$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.crearCiudadano$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `crearStaff()` */
  static readonly CrearStaffPath = '/interno/usuarios/staff';

  /**
   * Crear staff.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearStaff()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearStaff$Response(params: CrearStaff$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = crearStaff(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear staff.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearStaff$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearStaff(params: CrearStaff$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.crearStaff$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerUsuario()` */
  static readonly ObtenerUsuarioPath = '/interno/usuarios/{id}';

  /**
   * Obtener usuario por id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerUsuario()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerUsuario$Response(params: ObtenerUsuario$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = obtenerUsuario(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener usuario por id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerUsuario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerUsuario(params: ObtenerUsuario$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.obtenerUsuario$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerPorCedula()` */
  static readonly ObtenerPorCedulaPath = '/interno/usuarios/cedula/{cedula}';

  /**
   * Obtener usuario por cedula.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerPorCedula()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPorCedula$Response(params: ObtenerPorCedula$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = obtenerPorCedula(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener usuario por cedula.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerPorCedula$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPorCedula(params: ObtenerPorCedula$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.obtenerPorCedula$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `obtenerPublico()` */
  static readonly ObtenerPublicoPath = '/interno/usuarios/{id}/publico';

  /**
   * Obtener vista pública de usuario.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerPublico()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPublico$Response(params: ObtenerPublico$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioPublicoResponse>> {
    const obs = obtenerPublico(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener vista pública de usuario.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerPublico$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPublico(params: ObtenerPublico$Params, context?: HttpContext): Promise<UsuarioPublicoResponse> {
    const resp = this.obtenerPublico$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioPublicoResponse>): UsuarioPublicoResponse => r.body);
  }

  /** Path part for operation `actualizarAlias()` */
  static readonly ActualizarAliasPath = '/interno/usuarios/{id}/alias';

  /**
   * Actualizar alias público.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `actualizarAlias()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  actualizarAlias$Response(params: ActualizarAlias$Params, context?: HttpContext): Promise<StrictHttpResponse<AliasResponse>> {
    const obs = actualizarAlias(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Actualizar alias público.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `actualizarAlias$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  actualizarAlias(params: ActualizarAlias$Params, context?: HttpContext): Promise<AliasResponse> {
    const resp = this.actualizarAlias$Response(params, context);
    return resp.then((r: StrictHttpResponse<AliasResponse>): AliasResponse => r.body);
  }

  /** Path part for operation `usuarioInternoObtenerJefePorEntidad()` */
  static readonly UsuarioInternoObtenerJefePorEntidadPath = '/interno/usuarios/jefe';

  /**
   * Obtener jefe por entidad (interno).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usuarioInternoObtenerJefePorEntidad()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioInternoObtenerJefePorEntidad$Response(params: UsuarioInternoObtenerJefePorEntidad$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = usuarioInternoObtenerJefePorEntidad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener jefe por entidad (interno).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usuarioInternoObtenerJefePorEntidad$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioInternoObtenerJefePorEntidad(params: UsuarioInternoObtenerJefePorEntidad$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.usuarioInternoObtenerJefePorEntidad$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

  /** Path part for operation `usuarioInternoObtenerOperadoresPorEntidad()` */
  static readonly UsuarioInternoObtenerOperadoresPorEntidadPath = '/interno/usuarios/operadores';

  /**
   * Obtener operadores por entidad (interno).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usuarioInternoObtenerOperadoresPorEntidad()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioInternoObtenerOperadoresPorEntidad$Response(params: UsuarioInternoObtenerOperadoresPorEntidad$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioResponse>>> {
    const obs = usuarioInternoObtenerOperadoresPorEntidad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener operadores por entidad (interno).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usuarioInternoObtenerOperadoresPorEntidad$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usuarioInternoObtenerOperadoresPorEntidad(params: UsuarioInternoObtenerOperadoresPorEntidad$Params, context?: HttpContext): Promise<Array<UsuarioResponse>> {
    const resp = this.usuarioInternoObtenerOperadoresPorEntidad$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioResponse>>): Array<UsuarioResponse> => r.body);
  }

}
