/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { obtenerPerfil } from '../fn/perfil/obtener-perfil';
import { ObtenerPerfil$Params } from '../fn/perfil/obtener-perfil';
import { UsuarioResponse } from '../models/usuario-response';


/**
 * Endpoints para gestión del perfil del usuario logueado
 */
@Injectable({ providedIn: 'root' })
export class PerfilService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `obtenerPerfil()` */
  static readonly ObtenerPerfilPath = '/usuarios/me';

  /**
   * Obtener perfil del usuario autenticado.
   *
   * Retorna la información del usuario autenticado basado en el token JWT.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerPerfil()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPerfil$Response(params?: ObtenerPerfil$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioResponse>> {
    const obs = obtenerPerfil(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener perfil del usuario autenticado.
   *
   * Retorna la información del usuario autenticado basado en el token JWT.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerPerfil$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerPerfil(params?: ObtenerPerfil$Params, context?: HttpContext): Promise<UsuarioResponse> {
    const resp = this.obtenerPerfil$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioResponse>): UsuarioResponse => r.body);
  }

}
