/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { crearDenuncia } from '../fn/ciudadano/crear-denuncia';
import { CrearDenuncia$Params } from '../fn/ciudadano/crear-denuncia';
import { DenunciaCitizenViewResponse } from '../models/denuncia-citizen-view-response';
import { DenunciaResumenResponse } from '../models/denuncia-resumen-response';
import { denunciasMeGet } from '../fn/ciudadano/denuncias-me-get';
import { DenunciasMeGet$Params } from '../fn/ciudadano/denuncias-me-get';


/**
 * Creación y consulta propia.
 */
@Injectable({ providedIn: 'root' })
export class CiudadanoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `crearDenuncia()` */
  static readonly CrearDenunciaPath = '/denuncias';

  /**
   * Crear denuncia con nivel de privacidad.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearDenuncia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearDenuncia$Response(params: CrearDenuncia$Params, context?: HttpContext): Promise<StrictHttpResponse<DenunciaResumenResponse>> {
    const obs = crearDenuncia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear denuncia con nivel de privacidad.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearDenuncia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearDenuncia(params: CrearDenuncia$Params, context?: HttpContext): Promise<DenunciaResumenResponse> {
    const resp = this.crearDenuncia$Response(params, context);
    return resp.then((r: StrictHttpResponse<DenunciaResumenResponse>): DenunciaResumenResponse => r.body);
  }

  /** Path part for operation `denunciasMeGet()` */
  static readonly DenunciasMeGetPath = '/denuncias/me';

  /**
   * Mis Denuncias (Vista Ciudadano).
   *
   * Retorna SOLO las denuncias del usuario. Muestra el 'alias' del operador, no el nombre real.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `denunciasMeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  denunciasMeGet$Response(params?: DenunciasMeGet$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DenunciaCitizenViewResponse>>> {
    const obs = denunciasMeGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Mis Denuncias (Vista Ciudadano).
   *
   * Retorna SOLO las denuncias del usuario. Muestra el 'alias' del operador, no el nombre real.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `denunciasMeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  denunciasMeGet(params?: DenunciasMeGet$Params, context?: HttpContext): Promise<Array<DenunciaCitizenViewResponse>> {
    const resp = this.denunciasMeGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DenunciaCitizenViewResponse>>): Array<DenunciaCitizenViewResponse> => r.body);
  }

}
