/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { crearDenuncia } from '../fn/denuncias/crear-denuncia';
import { CrearDenuncia$Params } from '../fn/denuncias/crear-denuncia';
import { DenunciaListadoResponse } from '../models/denuncia-listado-response';
import { DenunciaResponse } from '../models/denuncia-response';
import { DenunciaResumenResponse } from '../models/denuncia-resumen-response';
import { listarDenuncias } from '../fn/denuncias/listar-denuncias';
import { ListarDenuncias$Params } from '../fn/denuncias/listar-denuncias';
import { obtenerDenunciaPorId } from '../fn/denuncias/obtener-denuncia-por-id';
import { ObtenerDenunciaPorId$Params } from '../fn/denuncias/obtener-denuncia-por-id';


/**
 * Creacion y consulta de denuncias.
 */
@Injectable({ providedIn: 'root' })
export class DenunciasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listarDenuncias()` */
  static readonly ListarDenunciasPath = '/';

  /**
   * Listar denuncias.
   *
   * Filtra denuncias según el rol y entidad del usuario autenticado (extraído del token).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarDenuncias()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarDenuncias$Response(params?: ListarDenuncias$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DenunciaListadoResponse>>> {
    const obs = listarDenuncias(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Listar denuncias.
   *
   * Filtra denuncias según el rol y entidad del usuario autenticado (extraído del token).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarDenuncias$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarDenuncias(params?: ListarDenuncias$Params, context?: HttpContext): Promise<Array<DenunciaListadoResponse>> {
    const resp = this.listarDenuncias$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DenunciaListadoResponse>>): Array<DenunciaListadoResponse> => r.body);
  }

  /** Path part for operation `crearDenuncia()` */
  static readonly CrearDenunciaPath = '/';

  /**
   * Crear denuncia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearDenuncia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearDenuncia$Response(params: CrearDenuncia$Params, context?: HttpContext): Promise<StrictHttpResponse<DenunciaResumenResponse>> {
    const obs = crearDenuncia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear denuncia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearDenuncia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearDenuncia(params: CrearDenuncia$Params, context?: HttpContext): Promise<DenunciaResumenResponse> {
    const resp = this.crearDenuncia$Response(params, context);
    return resp.then((r: StrictHttpResponse<DenunciaResumenResponse>): DenunciaResumenResponse => r.body);
  }

  /** Path part for operation `obtenerDenunciaPorId()` */
  static readonly ObtenerDenunciaPorIdPath = '/{denunciaId}';

  /**
   * Obtener denuncia por id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerDenunciaPorId()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerDenunciaPorId$Response(params: ObtenerDenunciaPorId$Params, context?: HttpContext): Promise<StrictHttpResponse<DenunciaResponse>> {
    const obs = obtenerDenunciaPorId(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener denuncia por id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerDenunciaPorId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerDenunciaPorId(params: ObtenerDenunciaPorId$Params, context?: HttpContext): Promise<DenunciaResponse> {
    const resp = this.obtenerDenunciaPorId$Response(params, context);
    return resp.then((r: StrictHttpResponse<DenunciaResponse>): DenunciaResponse => r.body);
  }

}
