/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { denunciasGestionGet } from '../fn/gestion-interna/denuncias-gestion-get';
import { DenunciasGestionGet$Params } from '../fn/gestion-interna/denuncias-gestion-get';
import { denunciasIdAsignacionPost } from '../fn/gestion-interna/denuncias-id-asignacion-post';
import { DenunciasIdAsignacionPost$Params } from '../fn/gestion-interna/denuncias-id-asignacion-post';
import { denunciasIdResolucionPatch } from '../fn/gestion-interna/denuncias-id-resolucion-patch';
import { DenunciasIdResolucionPatch$Params } from '../fn/gestion-interna/denuncias-id-resolucion-patch';
import { denunciasIdValidacionPatch } from '../fn/gestion-interna/denuncias-id-validacion-patch';
import { DenunciasIdValidacionPatch$Params } from '../fn/gestion-interna/denuncias-id-validacion-patch';
import { DenunciaStaffViewResponse } from '../models/denuncia-staff-view-response';


/**
 * Jefes, Operadores y Supervisores.
 */
@Injectable({ providedIn: 'root' })
export class GestionInternaService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `denunciasGestionGet()` */
  static readonly DenunciasGestionGetPath = '/denuncias/gestion';

  /**
   * Bandeja de entrada (Filtrada por Rol en Backend).
   *
   * - Jefe: Ve las de su área sin asignar. - Operador: Ve las asignadas a él. - Supervisor: Ve todas o las pendientes de validación.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `denunciasGestionGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  denunciasGestionGet$Response(params?: DenunciasGestionGet$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DenunciaStaffViewResponse>>> {
    const obs = denunciasGestionGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Bandeja de entrada (Filtrada por Rol en Backend).
   *
   * - Jefe: Ve las de su área sin asignar. - Operador: Ve las asignadas a él. - Supervisor: Ve todas o las pendientes de validación.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `denunciasGestionGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  denunciasGestionGet(params?: DenunciasGestionGet$Params, context?: HttpContext): Promise<Array<DenunciaStaffViewResponse>> {
    const resp = this.denunciasGestionGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DenunciaStaffViewResponse>>): Array<DenunciaStaffViewResponse> => r.body);
  }

  /** Path part for operation `denunciasIdAsignacionPost()` */
  static readonly DenunciasIdAsignacionPostPath = '/denuncias/{id}/asignacion';

  /**
   * Asignar operador (Solo Jefes).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `denunciasIdAsignacionPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciasIdAsignacionPost$Response(params: DenunciasIdAsignacionPost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = denunciasIdAsignacionPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Asignar operador (Solo Jefes).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `denunciasIdAsignacionPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciasIdAsignacionPost(params: DenunciasIdAsignacionPost$Params, context?: HttpContext): Promise<void> {
    const resp = this.denunciasIdAsignacionPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `denunciasIdResolucionPatch()` */
  static readonly DenunciasIdResolucionPatchPath = '/denuncias/{id}/resolucion';

  /**
   * Marcar como resuelta (Solo Operadores).
   *
   * Pasa el estado a 'EN_VALIDACION' (no visible aún como resuelta para el ciudadano).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `denunciasIdResolucionPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciasIdResolucionPatch$Response(params: DenunciasIdResolucionPatch$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = denunciasIdResolucionPatch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Marcar como resuelta (Solo Operadores).
   *
   * Pasa el estado a 'EN_VALIDACION' (no visible aún como resuelta para el ciudadano).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `denunciasIdResolucionPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciasIdResolucionPatch(params: DenunciasIdResolucionPatch$Params, context?: HttpContext): Promise<void> {
    const resp = this.denunciasIdResolucionPatch$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `denunciasIdValidacionPatch()` */
  static readonly DenunciasIdValidacionPatchPath = '/denuncias/{id}/validacion';

  /**
   * Aprobar o Rechazar solución (Solo Supervisor).
   *
   * Si aprueba -> Estado final RESUELTA (Ciudadano ve). Si rechaza -> Vuelve a EN_PROCESO.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `denunciasIdValidacionPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciasIdValidacionPatch$Response(params: DenunciasIdValidacionPatch$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = denunciasIdValidacionPatch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Aprobar o Rechazar solución (Solo Supervisor).
   *
   * Si aprueba -> Estado final RESUELTA (Ciudadano ve). Si rechaza -> Vuelve a EN_PROCESO.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `denunciasIdValidacionPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciasIdValidacionPatch(params: DenunciasIdValidacionPatch$Params, context?: HttpContext): Promise<void> {
    const resp = this.denunciasIdValidacionPatch$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
