/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { asignarEntidadADenuncia } from '../fn/workflow/asignar-entidad-a-denuncia';
import { AsignarEntidadADenuncia$Params } from '../fn/workflow/asignar-entidad-a-denuncia';
import { asignarOperadorAdenuncia } from '../fn/workflow/asignar-operador-adenuncia';
import { AsignarOperadorAdenuncia$Params } from '../fn/workflow/asignar-operador-adenuncia';
import { DenunciaEstadoHistorialResponse } from '../models/denuncia-estado-historial-response';
import { denunciaHistorialEstados } from '../fn/workflow/denuncia-historial-estados';
import { DenunciaHistorialEstados$Params } from '../fn/workflow/denuncia-historial-estados';
import { iniciarProcesoDenunciaOperadores } from '../fn/workflow/iniciar-proceso-denuncia-operadores';
import { IniciarProcesoDenunciaOperadores$Params } from '../fn/workflow/iniciar-proceso-denuncia-operadores';
import { rechazarDenuncia } from '../fn/workflow/rechazar-denuncia';
import { RechazarDenuncia$Params } from '../fn/workflow/rechazar-denuncia';
import { resolverDenuncia } from '../fn/workflow/resolver-denuncia';
import { ResolverDenuncia$Params } from '../fn/workflow/resolver-denuncia';
import { validarSolucionDenuncia } from '../fn/workflow/validar-solucion-denuncia';
import { ValidarSolucionDenuncia$Params } from '../fn/workflow/validar-solucion-denuncia';


/**
 * Asignacion, resolucion y validacion de denuncias.
 */
@Injectable({ providedIn: 'root' })
export class WorkflowService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `asignarEntidadADenuncia()` */
  static readonly AsignarEntidadADenunciaPath = '/{denunciaId}/asignacion-entidad';

  /**
   * Asignar entidad responsable.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `asignarEntidadADenuncia()` instead.
   *
   * This method doesn't expect any request body.
   */
  asignarEntidadADenuncia$Response(params: AsignarEntidadADenuncia$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = asignarEntidadADenuncia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Asignar entidad responsable.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `asignarEntidadADenuncia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  asignarEntidadADenuncia(params: AsignarEntidadADenuncia$Params, context?: HttpContext): Promise<void> {
    const resp = this.asignarEntidadADenuncia$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `asignarOperadorAdenuncia()` */
  static readonly AsignarOperadorAdenunciaPath = '/{denunciaId}/asignacion-operador';

  /**
   * Asignar operador a denuncia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `asignarOperadorAdenuncia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  asignarOperadorAdenuncia$Response(params: AsignarOperadorAdenuncia$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = asignarOperadorAdenuncia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Asignar operador a denuncia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `asignarOperadorAdenuncia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  asignarOperadorAdenuncia(params: AsignarOperadorAdenuncia$Params, context?: HttpContext): Promise<void> {
    const resp = this.asignarOperadorAdenuncia$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `iniciarProcesoDenunciaOperadores()` */
  static readonly IniciarProcesoDenunciaOperadoresPath = '/{denunciaId}/iniciar-proceso';

  /**
   * Iniciar proceso de denuncia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `iniciarProcesoDenunciaOperadores()` instead.
   *
   * This method doesn't expect any request body.
   */
  iniciarProcesoDenunciaOperadores$Response(params: IniciarProcesoDenunciaOperadores$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = iniciarProcesoDenunciaOperadores(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Iniciar proceso de denuncia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `iniciarProcesoDenunciaOperadores$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  iniciarProcesoDenunciaOperadores(params: IniciarProcesoDenunciaOperadores$Params, context?: HttpContext): Promise<void> {
    const resp = this.iniciarProcesoDenunciaOperadores$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `resolverDenuncia()` */
  static readonly ResolverDenunciaPath = '/{denunciaId}/resolucion';

  /**
   * Registrar resolucion de denuncia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resolverDenuncia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resolverDenuncia$Response(params: ResolverDenuncia$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = resolverDenuncia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Registrar resolucion de denuncia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resolverDenuncia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resolverDenuncia(params: ResolverDenuncia$Params, context?: HttpContext): Promise<void> {
    const resp = this.resolverDenuncia$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `validarSolucionDenuncia()` */
  static readonly ValidarSolucionDenunciaPath = '/{denunciaId}/validacion';

  /**
   * Validar solucion de denuncia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `validarSolucionDenuncia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validarSolucionDenuncia$Response(params: ValidarSolucionDenuncia$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = validarSolucionDenuncia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Validar solucion de denuncia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `validarSolucionDenuncia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validarSolucionDenuncia(params: ValidarSolucionDenuncia$Params, context?: HttpContext): Promise<void> {
    const resp = this.validarSolucionDenuncia$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `rechazarDenuncia()` */
  static readonly RechazarDenunciaPath = '/{denunciaId}/rechazo';

  /**
   * Rechazar denuncia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rechazarDenuncia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rechazarDenuncia$Response(params: RechazarDenuncia$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = rechazarDenuncia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rechazar denuncia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rechazarDenuncia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rechazarDenuncia(params: RechazarDenuncia$Params, context?: HttpContext): Promise<void> {
    const resp = this.rechazarDenuncia$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `denunciaHistorialEstados()` */
  static readonly DenunciaHistorialEstadosPath = '/{denunciaId}/historial-estados';

  /**
   * Historial de estados de la denuncia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `denunciaHistorialEstados()` instead.
   *
   * This method doesn't expect any request body.
   */
  denunciaHistorialEstados$Response(params: DenunciaHistorialEstados$Params, context?: HttpContext): Promise<StrictHttpResponse<DenunciaEstadoHistorialResponse>> {
    const obs = denunciaHistorialEstados(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Historial de estados de la denuncia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `denunciaHistorialEstados$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  denunciaHistorialEstados(params: DenunciaHistorialEstados$Params, context?: HttpContext): Promise<DenunciaEstadoHistorialResponse> {
    const resp = this.denunciaHistorialEstados$Response(params, context);
    return resp.then((r: StrictHttpResponse<DenunciaEstadoHistorialResponse>): DenunciaEstadoHistorialResponse => r.body);
  }

}
